// reactions.js - the verified reaction table for The Tree of Organic.
//
// One entry per reaction the DAT can ask. Structures are SMILES so the shell
// can draw them; products are the MAJOR organic product on the canonical
// substrate. Names, outcomes and tags come from the Ace Labs engine's
// reaction map (105 reactions, dat-sme verified 2026-07) and Thomas's content
// atoms; the SMILES and the extra entries were added 2026-09-03 and checked by
// rendering every one through the SMILES parser. Generators build items FROM
// this table and take distractors from siblings, never from thin air.
//
// Fields: id, family, name, reagent (label shown on the arrow), cond (second
// line on the arrow), subClass, sub, prod, prodNote (other products or
// stereo detail in words), regio, stereo, mech (family), steps (the move in
// plain words, 2 to 4), thomas (his line), trap, roots (best first), booster.

export const SUBSTRATES = {
  alkene_terminal: { name: 'propene', smi: 'C=CC' },
  alkene_internal: { name: 'trans-2-butene', smi: 'C/C=C/C' },
  alkene_branched: { name: '3-methyl-1-butene', smi: 'C=CC(C)C' },
  alkene_trisub: { name: '2-methyl-2-butene', smi: 'CC=C(C)C' },
  alkyne_terminal: { name: '1-butyne', smi: 'CCC#C' },
  alkyne_internal: { name: '2-butyne', smi: 'CC#CC' },
  alcohol_primary: { name: '1-propanol', smi: 'CCCO' },
  alcohol_secondary: { name: '2-propanol', smi: 'CC(C)O' },
  alcohol_tertiary: { name: 'tert-butanol', smi: 'CC(C)(C)O' },
  halide_primary: { name: '1-bromopropane', smi: 'CCCBr' },
  halide_secondary: { name: '2-bromopropane', smi: 'CC(C)Br' },
  halide_tertiary: { name: 'tert-butyl bromide', smi: 'CC(C)(C)Br' },
  halide_tertiary_b: { name: '2-bromo-2-methylbutane', smi: 'CCC(C)(C)Br' },
  aldehyde: { name: 'propanal', smi: 'CCC=O' },
  acetaldehyde: { name: 'acetaldehyde', smi: 'CC=O' },
  ketone: { name: '2-butanone', smi: 'CCC(C)=O' },
  acetone: { name: 'acetone', smi: 'CC(C)=O' },
  acid: { name: 'acetic acid', smi: 'CC(=O)O' },
  ester: { name: 'methyl acetate', smi: 'COC(C)=O' },
  ethyl_acetate: { name: 'ethyl acetate', smi: 'CCOC(C)=O' },
  amide: { name: 'acetamide', smi: 'CC(N)=O' },
  nitrile: { name: 'propanenitrile', smi: 'CCC#N' },
  acid_chloride: { name: 'acetyl chloride', smi: 'CC(=O)Cl' },
  benzene: { name: 'benzene', smi: 'c1ccccc1' },
  toluene: { name: 'toluene', smi: 'Cc1ccccc1' },
  anisole: { name: 'anisole', smi: 'COc1ccccc1' },
  nitrobenzene: { name: 'nitrobenzene', smi: '[O-][N+](=O)c1ccccc1' },
  chlorobenzene: { name: 'chlorobenzene', smi: 'Clc1ccccc1' },
  aniline: { name: 'aniline', smi: 'Nc1ccccc1' },
  epoxide: { name: 'propylene oxide', smi: 'CC1CO1' },
  alkane: { name: '2-methylpropane', smi: 'CC(C)C' },
  diene: { name: '1,3-butadiene', smi: 'C=CC=C' },
  betaketoacid: { name: 'acetoacetic acid', smi: 'CC(=O)CC(=O)O' },
  diketone: { name: 'acetylacetone', smi: 'CC(=O)CC(C)=O' }
};
const S = SUBSTRATES;
function rx(o){ return Object.assign({ cond: '', prodNote: '', regio: '', stereo: '', steps: [], roots: [] }, o); }

export const REACTIONS = [
  // ---------------- ALKENES ----------------
  rx({ id: 'alkene_hbr', family: 'alkenes', name: 'HBr addition (Markovnikov)', reagent: 'HBr', subClass: 'alkene_terminal', sub: S.alkene_terminal.smi, prod: 'CC(C)Br', regio: 'Markovnikov: Br on the more substituted carbon', stereo: 'racemic where a center forms', mech: 'electrophilic addition, carbocation', steps: ['The pi bond grabs H+ so the plus lands on the more substituted carbon.', 'Bromide attacks the carbocation.'], thomas: 'The rich get richer: H goes where the H\'s already are, Br takes the crowded carbon.', trap: 'A carbocation can rearrange; check for a better neighbor before you place the Br.', roots: ['l2-carbocation', 'l2-arrows'], booster: 'Alkene Addition Reactions' }),
  rx({ id: 'alkene_hbr_peroxide', family: 'alkenes', name: 'HBr with peroxide (anti-Markovnikov)', reagent: 'HBr', cond: 'ROOR', subClass: 'alkene_terminal', sub: S.alkene_terminal.smi, prod: 'CCCBr', regio: 'anti-Markovnikov: Br on the less substituted carbon', stereo: 'none', mech: 'radical addition', steps: ['Peroxide makes a bromine radical.', 'Br adds first to the less substituted carbon, leaving the more stable radical.', 'The radical takes H from HBr.'], thomas: 'Peroxide means anti-Markovnikov, every time.', trap: 'Only HBr does this; HCl and HI with peroxide still go Markovnikov.', roots: ['l2-carbocation', 'l2-arrows'], booster: 'Alkene Addition Reactions' }),
  rx({ id: 'alkene_h3o', family: 'alkenes', name: 'Acid-catalyzed hydration', reagent: 'H3O+', cond: 'H2O, H2SO4', subClass: 'alkene_terminal', sub: S.alkene_terminal.smi, prod: 'CC(C)O', regio: 'Markovnikov OH', stereo: 'racemic', mech: 'electrophilic addition, carbocation', steps: ['Protonate the alkene to the more stable carbocation.', 'Water attacks, then loses a proton.'], thomas: 'Same story as HBr with water as the nucleophile. Rearrangements are on the table.', trap: 'This one can rearrange; oxymercuration is the no-rearrangement version.', roots: ['l2-carbocation', 'l2-arrows'], booster: 'Alkene Addition Reactions' }),
  rx({ id: 'alkene_oxymerc', family: 'alkenes', name: 'Oxymercuration-demercuration', reagent: '1. Hg(OAc)2, H2O', cond: '2. NaBH4', subClass: 'alkene_terminal', sub: S.alkene_terminal.smi, prod: 'CC(C)O', regio: 'Markovnikov OH', stereo: 'anti addition, no rearrangement', mech: 'electrophilic addition, bridged mercurinium', steps: ['Mercury bridges the alkene, no free carbocation.', 'Water opens the bridge at the more substituted carbon.', 'NaBH4 swaps the mercury for H.'], thomas: 'M for mercury, M for Markovnikov, and no rearrangement because the bridge never lets a carbocation form.', trap: 'Same product as acid hydration on a simple alkene; the difference shows up when a rearrangement is possible.', roots: ['l2-carbocation', 'l2-arrows'], booster: 'Alkene Addition Reactions' }),
  rx({ id: 'alkene_hydroboration', family: 'alkenes', name: 'Hydroboration-oxidation', reagent: '1. BH3, THF', cond: '2. H2O2, NaOH', subClass: 'alkene_terminal', sub: S.alkene_terminal.smi, prod: 'CCCO', regio: 'anti-Markovnikov OH', stereo: 'syn addition', mech: 'concerted addition', steps: ['Boron and H add to the same face in one step, boron on the less crowded carbon.', 'Peroxide swaps boron for OH with retention.'], thomas: 'Weird address, same-side parking: anti-Markovnikov and syn at the same time.', trap: 'Anti-Markovnikov is about which carbon; anti-addition is about which face. Hydroboration is anti-Markovnikov and SYN.', roots: ['l2-bully', 'l2-arrows'], booster: 'Alkene Addition Reactions' }),
  rx({ id: 'alkene_h2', family: 'alkenes', name: 'Catalytic hydrogenation', reagent: 'H2', cond: 'Pt, Pd or Ni', subClass: 'alkene_terminal', sub: S.alkene_terminal.smi, prod: 'CCC', stereo: 'syn addition', mech: 'catalytic surface addition', steps: ['Both H atoms add from the metal surface to the same face.'], thomas: 'The pi bond is gone and two hydrogens took its place, same side.', trap: 'Hydrogenation does not touch a carbonyl or an aromatic ring under these conditions.', roots: ['l1-unsat'], booster: 'Alkene Addition Reactions' }),
  rx({ id: 'alkene_br2', family: 'alkenes', name: 'Bromination', reagent: 'Br2', cond: 'CCl4', subClass: 'alkene_terminal', sub: S.alkene_terminal.smi, prod: 'CC(Br)CBr', stereo: 'anti addition through the bromonium ion', mech: 'electrophilic addition, bridged halonium', steps: ['The pi bond attacks Br2 and makes a three-membered bromonium ring.', 'Bromide opens it from the back side.'], thomas: 'The bridge forces the second bromine to come from the opposite face.', trap: 'No carbocation, so no rearrangement, and the addition is anti, not syn.', roots: ['l2-arrows', 'l3-isomers'], booster: 'Alkene Addition Reactions' }),
  rx({ id: 'alkene_halohydrin', family: 'alkenes', name: 'Halohydrin formation', reagent: 'Br2', cond: 'H2O', subClass: 'alkene_terminal', sub: S.alkene_terminal.smi, prod: 'CC(O)CBr', regio: 'OH on the more substituted carbon', stereo: 'anti', mech: 'electrophilic addition, bridged halonium', steps: ['Bromonium forms as before.', 'Water, the solvent, opens it at the more substituted carbon from the back side.'], thomas: 'Same bridge, but water wins the fight because there is an ocean of it.', trap: 'The OH goes to the more substituted carbon (Markovnikov-like), the Br to the other.', roots: ['l2-carbocation', 'l2-arrows'], booster: 'Alkene Addition Reactions' }),
  rx({ id: 'alkene_mcpba', family: 'alkenes', name: 'Epoxidation', reagent: 'mCPBA', subClass: 'alkene_terminal', sub: S.alkene_terminal.smi, prod: 'CC1CO1', stereo: 'syn, alkene geometry kept', mech: 'concerted oxygen transfer', steps: ['The peroxyacid hands one oxygen to the alkene in a single step.'], thomas: 'One oxygen, one step, both new bonds on the same face.', trap: 'A cis alkene gives a cis epoxide; the geometry survives.', roots: ['l2-arrows', 'l3-ez'], booster: 'Alkene Addition Reactions' }),
  rx({ id: 'alkene_oso4', family: 'alkenes', name: 'Syn dihydroxylation', reagent: 'OsO4', cond: 'or cold, dilute KMnO4', subClass: 'alkene_terminal', sub: S.alkene_terminal.smi, prod: 'CC(O)CO', stereo: 'syn diol', mech: 'concerted cyclic addition', steps: ['A cyclic osmate ester forms on one face.', 'Workup releases the diol with both OH on that face.'], thomas: 'Cold KMnO4 gives the syn diol. Hot KMnO4 cuts the bond. Temperature is the whole question.', trap: 'Cold and dilute makes the diol; hot and concentrated cleaves to acids.', roots: ['l3-isomers', 'l2-arrows'], booster: 'Alkene Addition Reactions' }),
  rx({ id: 'alkene_o3_zn', family: 'alkenes', name: 'Ozonolysis, reductive workup', reagent: '1. O3', cond: '2. Zn, H2O (or DMS)', subClass: 'alkene_terminal', sub: S.alkene_terminal.smi, prod: 'CC=O', prodNote: 'plus formaldehyde from the CH2 end', mech: 'oxidative cleavage', steps: ['Ozone cuts the double bond in two.', 'Zn or DMS keeps each half at the aldehyde or ketone stage.'], thomas: 'Ozonolysis cuts right through. Zinc keeps the aldehydes as aldehydes.', trap: 'A CH2 end becomes formaldehyde; a disubstituted end becomes a ketone.', roots: ['l1-groups', 'l1-unsat'], booster: 'Alkene Addition Reactions' }),
  rx({ id: 'alkene_o3_h2o2', family: 'alkenes', name: 'Ozonolysis, oxidative workup', reagent: '1. O3', cond: '2. H2O2', subClass: 'alkene_terminal', sub: S.alkene_terminal.smi, prod: 'CC(=O)O', prodNote: 'plus CO2 from the CH2 end', mech: 'oxidative cleavage', steps: ['Ozone cuts the double bond.', 'Peroxide pushes any aldehyde up to the carboxylic acid.'], thomas: 'Same cut, but peroxide will not let an aldehyde stay an aldehyde.', trap: 'A ketone end stays a ketone; only aldehyde ends climb to acids.', roots: ['l1-groups'], booster: 'Alkene Addition Reactions' }),
  rx({ id: 'alkene_kmno4_hot', family: 'alkenes', name: 'Hot permanganate cleavage', reagent: 'KMnO4', cond: 'hot, concentrated', subClass: 'alkene_terminal', sub: S.alkene_terminal.smi, prod: 'CC(=O)O', prodNote: 'plus CO2', mech: 'oxidative cleavage', steps: ['Hot permanganate cleaves the alkene and oxidizes the fragments as far as they go.'], thomas: 'Hot KMnO4 is the flamethrower.', trap: 'Cold and dilute is the gentle syn diol; hot is cleavage.', roots: ['l1-groups'], booster: 'Alkene Addition Reactions' }),
  rx({ id: 'alkene_int_h2', family: 'alkenes', name: 'Hydrogenation of an internal alkene', reagent: 'H2', cond: 'Pt', subClass: 'alkene_internal', sub: S.alkene_internal.smi, prod: 'CCCC', stereo: 'syn', mech: 'catalytic surface addition', steps: ['Both hydrogens add from the metal surface.'], thomas: 'Butene to butane. Nothing else changes.', trap: 'Cis and trans give the same alkane.', roots: ['l1-unsat'], booster: 'Alkene Addition Reactions' }),
  rx({ id: 'alkene_int_hbr', family: 'alkenes', name: 'HBr on a symmetric internal alkene', reagent: 'HBr', subClass: 'alkene_internal', sub: S.alkene_internal.smi, prod: 'CCC(C)Br', regio: 'either carbon, same product', stereo: 'racemic', mech: 'electrophilic addition, carbocation', steps: ['Protonate to a secondary carbocation.', 'Bromide attacks either face.'], thomas: 'Symmetric alkene, so Markovnikov has nothing to decide. The new center is racemic.', trap: 'A plane of symmetry means both carbons are the same address.', roots: ['l2-carbocation', 'l3-isomers'], booster: 'Alkene Addition Reactions' }),
  rx({ id: 'alkene_int_br2', family: 'alkenes', name: 'Bromination of trans-2-butene', reagent: 'Br2', cond: 'CCl4', subClass: 'alkene_internal', sub: S.alkene_internal.smi, prod: 'C[C@@H](Br)[C@H](C)Br', prodNote: 'anti addition to the trans alkene gives the meso dibromide', stereo: 'anti, meso product', mech: 'electrophilic addition, bridged halonium', steps: ['Bromonium forms.', 'Bromide opens it from the back.'], thomas: 'Trans plus anti gives meso. Cis plus anti gives the racemic pair. That is a favorite question.', trap: 'The alkene geometry decides which stereoisomers come out.', roots: ['l3-isomers', 'l3-ez'], booster: 'Alkene Addition Reactions' }),
  rx({ id: 'alkene_int_o3', family: 'alkenes', name: 'Ozonolysis of 2-butene', reagent: '1. O3', cond: '2. Zn, H2O', subClass: 'alkene_internal', sub: S.alkene_internal.smi, prod: 'CC=O', prodNote: 'two molecules of acetaldehyde', mech: 'oxidative cleavage', steps: ['Cut the double bond; each half keeps its substituents.'], thomas: 'Draw the scissors through the double bond and put an O on each cut end.', trap: 'Count carbons on each side of the cut before you name the fragments.', roots: ['l1-skeletal', 'l1-groups'], booster: 'Alkene Addition Reactions' }),
  rx({ id: 'alkene_int_oso4', family: 'alkenes', name: 'Syn dihydroxylation of 2-butene', reagent: 'OsO4', cond: 'or cold KMnO4', subClass: 'alkene_internal', sub: S.alkene_internal.smi, prod: 'C[C@@H](O)[C@@H](C)O', prodNote: 'syn addition to the trans alkene gives the racemic pair; the cis alkene gives meso', stereo: 'syn', mech: 'concerted cyclic addition', steps: ['Both OH land on the same face.'], thomas: 'Syn on trans gives the pair; syn on cis gives meso. Opposite of bromination.', trap: 'Syn versus anti and cis versus trans combine to decide meso or racemic.', roots: ['l3-isomers', 'l3-ez'], booster: 'Alkene Addition Reactions' }),
  rx({ id: 'alkene_rearr_hbr', family: 'alkenes', name: 'HBr with a hydride shift', reagent: 'HBr', subClass: 'alkene_branched', sub: S.alkene_branched.smi, prod: 'CCC(C)(C)Br', regio: 'after a 1,2-hydride shift the bromide lands on the tertiary carbon', mech: 'electrophilic addition, carbocation rearrangement', steps: ['Protonation gives a secondary carbocation next to a tertiary carbon.', 'A hydride slides over to make the tertiary cation.', 'Bromide attacks the tertiary carbon.'], thomas: 'If you are ever surprised by a rearrangement, carbocation stability is the root that was missing.', trap: 'The Br is not where Markovnikov first put it; the cation moved.', roots: ['l2-carbocation'], booster: 'Alkene Addition Reactions' }),
  rx({ id: 'alkene_trisub_o3', family: 'alkenes', name: 'Ozonolysis of a trisubstituted alkene', reagent: '1. O3', cond: '2. Zn, H2O', subClass: 'alkene_trisub', sub: S.alkene_trisub.smi, prod: 'CC(C)=O', prodNote: 'acetone plus acetaldehyde', mech: 'oxidative cleavage', steps: ['Cut the bond; the disubstituted end becomes a ketone, the monosubstituted end an aldehyde.'], thomas: 'One side is a ketone, the other an aldehyde. Count carbons on each side.', trap: 'A ketone end cannot be pushed further even with peroxide.', roots: ['l1-groups', 'l1-skeletal'], booster: 'Alkene Addition Reactions' }),

  // ---------------- ALKYNES ----------------
  rx({ id: 'alkyne_lindlar', family: 'alkynes', name: 'Lindlar hydrogenation', reagent: 'H2', cond: "Lindlar's catalyst", subClass: 'alkyne_terminal', sub: S.alkyne_terminal.smi, prod: 'CCC=C', stereo: 'syn, stops at the alkene', mech: 'catalytic surface addition', steps: ['Poisoned palladium adds one H2 and stops.'], thomas: 'Lindlar, L for lazy: one hydrogen and it quits. C for cis when the alkyne is internal.', trap: 'A terminal alkyne has no cis or trans to make.', roots: ['l3-ez', 'l1-unsat'], booster: 'Alkyne Reactions' }),
  rx({ id: 'alkyne_na_nh3', family: 'alkynes', name: 'Dissolving metal reduction', reagent: 'Na', cond: 'NH3 (liquid)', subClass: 'alkyne_terminal', sub: S.alkyne_terminal.smi, prod: 'CCC=C', stereo: 'anti, trans alkene when internal', mech: 'radical anion reduction', steps: ['Sodium hands over an electron, ammonia hands over a proton, twice.'], thomas: 'Sodium in ammonia is the trans maker.', trap: 'Terminal alkyne: same product as Lindlar because there is no cis or trans.', roots: ['l3-ez'], booster: 'Alkyne Reactions' }),
  rx({ id: 'alkyne_h2_pt', family: 'alkynes', name: 'Full hydrogenation', reagent: 'H2 (excess)', cond: 'Pt', subClass: 'alkyne_terminal', sub: S.alkyne_terminal.smi, prod: 'CCCC', mech: 'catalytic surface addition', steps: ['Two equivalents of H2 all the way to the alkane.'], thomas: 'Platinum does not stop. Two pi bonds, two H2.', trap: 'Only Lindlar or Na/NH3 stop at the alkene.', roots: ['l1-unsat'], booster: 'Alkyne Reactions' }),
  rx({ id: 'alkyne_hg_h2o', family: 'alkynes', name: 'Mercury-catalyzed hydration', reagent: 'H2O, H2SO4', cond: 'HgSO4', subClass: 'alkyne_terminal', sub: S.alkyne_terminal.smi, prod: 'CCC(C)=O', regio: 'Markovnikov, methyl ketone', mech: 'addition then keto-enol tautomerization', steps: ['Water adds Markovnikov to give an enol.', 'The enol tautomerizes to the ketone.'], thomas: 'Terminal alkyne plus mercury water makes a methyl ketone, every time.', trap: 'The enol is never the answer; it becomes the ketone.', roots: ['l2-carbocation', 'l2-resonance'], booster: 'Alkyne Reactions' }),
  rx({ id: 'alkyne_hydroboration', family: 'alkynes', name: 'Hydroboration of an alkyne', reagent: '1. BH3 (or R2BH)', cond: '2. H2O2, NaOH', subClass: 'alkyne_terminal', sub: S.alkyne_terminal.smi, prod: 'CCCC=O', regio: 'anti-Markovnikov, aldehyde', mech: 'concerted addition then tautomerization', steps: ['Boron takes the terminal carbon.', 'Oxidation gives an enol that tautomerizes to the aldehyde.'], thomas: 'Boron always takes the open end. On a terminal alkyne that means an aldehyde.', trap: 'Mercury gives the methyl ketone; boron gives the aldehyde.', roots: ['l2-bully'], booster: 'Alkyne Reactions' }),
  rx({ id: 'alkyne_hx_once', family: 'alkynes', name: 'One equivalent of HBr', reagent: 'HBr (1 equiv)', subClass: 'alkyne_terminal', sub: S.alkyne_terminal.smi, prod: 'CCC(Br)=C', regio: 'Markovnikov vinyl bromide', mech: 'electrophilic addition', steps: ['Protonate the triple bond at the terminal carbon.', 'Bromide attacks the internal vinyl cation.'], thomas: 'One HBr, one Markovnikov addition, and you stop at the vinyl halide.', trap: 'Count the equivalents; the second HBr goes to the same carbon.', roots: ['l2-carbocation'], booster: 'Alkyne Reactions' }),
  rx({ id: 'alkyne_hx_twice', family: 'alkynes', name: 'Excess HBr', reagent: 'HBr (2 equiv)', subClass: 'alkyne_terminal', sub: S.alkyne_terminal.smi, prod: 'CCC(C)(Br)Br', regio: 'geminal dibromide', mech: 'electrophilic addition, twice', steps: ['The second addition is Markovnikov again, onto the carbon that already holds the bromine.'], thomas: 'Add HBr twice and both bromines pile onto the same carbon.', trap: 'Geminal, not vicinal.', roots: ['l2-carbocation', 'l2-resonance'], booster: 'Alkyne Reactions' }),
  rx({ id: 'alkyne_nanh2', family: 'alkynes', name: 'Acetylide formation', reagent: 'NaNH2', subClass: 'alkyne_terminal', sub: S.alkyne_terminal.smi, prod: 'CCC#[C-]', prodNote: 'the acetylide anion, a carbon nucleophile', mech: 'acid-base', steps: ['Amide takes the sp C-H, the most acidic hydrocarbon proton.'], thomas: 'That is not a reaction, that is acid-base chemistry. The sp hydrogen is acidic enough for NaNH2.', trap: 'Only a terminal alkyne has that proton.', roots: ['l2-acidity', 'l1-geometry'], booster: 'Alkyne Reactions' }),
  rx({ id: 'alkyne_alkylation', family: 'alkynes', name: 'Acetylide alkylation', reagent: '1. NaNH2', cond: '2. CH3Br', subClass: 'alkyne_terminal', sub: S.alkyne_terminal.smi, prod: 'CCC#CC', mech: 'acid-base then SN2', steps: ['Make the acetylide.', 'The acetylide attacks a primary halide by SN2.'], thomas: 'Build the carbon chain: deprotonate, then attack a primary halide.', trap: 'Secondary and tertiary halides eliminate instead.', roots: ['l2-acidity', 'l2-arrows'], booster: 'Alkyne Reactions' }),
  rx({ id: 'alkyne_int_lindlar', family: 'alkynes', name: 'Lindlar on an internal alkyne', reagent: 'H2', cond: "Lindlar's catalyst", subClass: 'alkyne_internal', sub: S.alkyne_internal.smi, prod: 'C/C=C\\C', stereo: 'cis alkene', mech: 'catalytic surface addition', steps: ['Syn addition of one H2.'], thomas: 'Catalyst C, cis.', trap: 'Cis from Lindlar, trans from sodium.', roots: ['l3-ez'], booster: 'Alkyne Reactions' }),
  rx({ id: 'alkyne_int_na', family: 'alkynes', name: 'Na/NH3 on an internal alkyne', reagent: 'Na', cond: 'NH3 (liquid)', subClass: 'alkyne_internal', sub: S.alkyne_internal.smi, prod: 'C/C=C/C', stereo: 'trans alkene', mech: 'radical anion reduction', steps: ['Anti addition of two H.'], thomas: 'Sodium in ammonia, trans.', trap: 'This is the only common way to a trans alkene from an alkyne.', roots: ['l3-ez'], booster: 'Alkyne Reactions' }),
  rx({ id: 'alkyne_int_o3', family: 'alkynes', name: 'Ozonolysis of an alkyne', reagent: '1. O3', cond: '2. H2O', subClass: 'alkyne_internal', sub: S.alkyne_internal.smi, prod: 'CC(=O)O', prodNote: 'two molecules of acetic acid', mech: 'oxidative cleavage', steps: ['Cut the triple bond; each end becomes a carboxylic acid.'], thomas: 'A triple bond cut gives acids, not aldehydes.', trap: 'Alkenes give aldehydes with Zn; alkynes give acids.', roots: ['l1-groups'], booster: 'Alkyne Reactions' }),

  // ---------------- ALCOHOLS ----------------
  rx({ id: 'alc1_pcc', family: 'alcohols', name: 'PCC oxidation of a primary alcohol', reagent: 'PCC', cond: 'CH2Cl2', subClass: 'alcohol_primary', sub: S.alcohol_primary.smi, prod: 'CCC=O', mech: 'oxidation', steps: ['Add one bond to oxygen and stop.'], thomas: 'PCC is the gentle one: a primary alcohol stops at the aldehyde.', trap: 'Jones would keep going to the acid.', roots: ['l1-groups'], booster: 'Alcohols, Ethers, & Epoxides' }),
  rx({ id: 'alc1_jones', family: 'alcohols', name: 'Jones oxidation of a primary alcohol', reagent: 'CrO3, H2SO4', cond: 'acetone, H2O', subClass: 'alcohol_primary', sub: S.alcohol_primary.smi, prod: 'CCC(=O)O', mech: 'oxidation', steps: ['Alcohol to aldehyde to acid, no stopping.'], thomas: 'Chromium Jones, the strong one. They hide the H2SO4 to trick you.', trap: 'The hidden acid is the tell that it goes all the way.', roots: ['l1-groups'], booster: 'Alcohols, Ethers, & Epoxides' }),
  rx({ id: 'alc2_pcc', family: 'alcohols', name: 'PCC oxidation of a secondary alcohol', reagent: 'PCC', cond: 'CH2Cl2', subClass: 'alcohol_secondary', sub: S.alcohol_secondary.smi, prod: 'CC(C)=O', mech: 'oxidation', steps: ['Secondary alcohol to ketone.'], thomas: 'A secondary alcohol only has one place to go: the ketone.', trap: 'Strong or weak, a secondary alcohol stops at the ketone.', roots: ['l1-groups'], booster: 'Alcohols, Ethers, & Epoxides' }),
  rx({ id: 'alc2_jones', family: 'alcohols', name: 'Jones oxidation of a secondary alcohol', reagent: 'CrO3, H2SO4', subClass: 'alcohol_secondary', sub: S.alcohol_secondary.smi, prod: 'CC(C)=O', mech: 'oxidation', steps: ['Secondary alcohol to ketone, and the ketone cannot climb further.'], thomas: 'Same ketone. There is no H left on that carbon to take.', trap: 'No overshoot possible from a ketone.', roots: ['l1-groups'], booster: 'Alcohols, Ethers, & Epoxides' }),
  rx({ id: 'alc3_jones', family: 'alcohols', name: 'Jones on a tertiary alcohol', reagent: 'CrO3, H2SO4', subClass: 'alcohol_tertiary', sub: S.alcohol_tertiary.smi, prod: 'CC(C)(C)O', prodNote: 'no reaction', mech: 'none', steps: ['No H on the carbon holding the OH, so nothing to oxidize.'], thomas: 'A tertiary alcohol will not oxidize. There is no H on the carbon holding the OH.', trap: 'No reaction is a legitimate answer.', roots: ['l1-skeletal'], booster: 'Alcohols, Ethers, & Epoxides' }),
  rx({ id: 'alc1_socl2', family: 'alcohols', name: 'SOCl2 on a primary alcohol', reagent: 'SOCl2', cond: 'pyridine', subClass: 'alcohol_primary', sub: S.alcohol_primary.smi, prod: 'CCCCl', mech: 'SN2 via chlorosulfite', steps: ['OH becomes a chlorosulfite leaving group.', 'Chloride attacks by SN2.'], thomas: 'SOCl2, suckle too: swaps OH for Cl.', trap: 'No rearrangement; it is SN2, so a stereocenter inverts.', roots: ['l2-arrows'], booster: 'Alcohols, Ethers, & Epoxides' }),
  rx({ id: 'alc2_socl2', family: 'alcohols', name: 'SOCl2 on a secondary alcohol', reagent: 'SOCl2', cond: 'pyridine', subClass: 'alcohol_secondary', sub: S.alcohol_secondary.smi, prod: 'CC(C)Cl', mech: 'SN2 via chlorosulfite', steps: ['Same swap, inversion at the carbon.'], thomas: 'Suckle too again. Same move on a secondary carbon.', trap: 'Inversion if the carbon is a stereocenter.', roots: ['l2-arrows', 'l3-wedge'], booster: 'Alcohols, Ethers, & Epoxides' }),
  rx({ id: 'alc1_pbr3', family: 'alcohols', name: 'PBr3 on a primary alcohol', reagent: 'PBr3', subClass: 'alcohol_primary', sub: S.alcohol_primary.smi, prod: 'CCCBr', mech: 'SN2 via phosphite ester', steps: ['OH becomes a good leaving group on phosphorus.', 'Bromide attacks by SN2.'], thomas: 'PBr3, shit beers: replace the OH with a beer.', trap: 'No carbocation, no rearrangement.', roots: ['l2-arrows'], booster: 'Alcohols, Ethers, & Epoxides' }),
  rx({ id: 'alc2_pbr3', family: 'alcohols', name: 'PBr3 on a secondary alcohol', reagent: 'PBr3', subClass: 'alcohol_secondary', sub: S.alcohol_secondary.smi, prod: 'CC(C)Br', stereo: 'inversion', mech: 'SN2 via phosphite ester', steps: ['Same swap, backside attack.'], thomas: 'Same beer, inverted center.', trap: 'HBr on the same alcohol would go through a carbocation and could rearrange.', roots: ['l2-arrows', 'l3-wedge'], booster: 'Alcohols, Ethers, & Epoxides' }),
  rx({ id: 'alc3_socl2', family: 'alcohols', name: 'SOCl2 on a tertiary alcohol', reagent: 'SOCl2', subClass: 'alcohol_tertiary', sub: S.alcohol_tertiary.smi, prod: 'CC(C)(C)Cl', mech: 'SN1-like', steps: ['The tertiary carbon lets the leaving group go on its own; chloride fills the cation.'], thomas: 'A tertiary carbon never takes a backside attack, so this one goes through the cation.', trap: 'Tertiary means SN1, not SN2.', roots: ['l2-carbocation'], booster: 'Alcohols, Ethers, & Epoxides' }),
  rx({ id: 'alc3_hbr', family: 'alcohols', name: 'HBr on a tertiary alcohol', reagent: 'HBr', subClass: 'alcohol_tertiary', sub: S.alcohol_tertiary.smi, prod: 'CC(C)(C)Br', mech: 'SN1', steps: ['Protonate the OH to water.', 'Water leaves to give the tertiary cation.', 'Bromide attacks.'], thomas: 'Protonate, leave, attack. The tertiary cation makes it easy.', trap: 'Primary alcohols need PBr3 or SOCl2 instead; HBr on a primary is slow SN2.', roots: ['l2-carbocation', 'l2-acidity'], booster: 'Alcohols, Ethers, & Epoxides' }),
  rx({ id: 'alc3_dehydration', family: 'alcohols', name: 'Acid dehydration of a tertiary alcohol', reagent: 'H2SO4', cond: 'heat', subClass: 'alcohol_tertiary', sub: S.alcohol_tertiary.smi, prod: 'C=C(C)C', regio: 'Zaitsev', mech: 'E1', steps: ['Protonate the OH, lose water to a tertiary cation.', 'Lose a beta proton to the more substituted alkene.'], thomas: 'Heat plus acid on an alcohol is elimination, and E1 gives the Zaitsev alkene.', trap: 'E1 carbocations can rearrange before eliminating.', roots: ['l2-carbocation'], booster: 'Alcohols, Ethers, & Epoxides' }),
  rx({ id: 'alc2_dehydration', family: 'alcohols', name: 'Acid dehydration of a secondary alcohol', reagent: 'H2SO4', cond: 'heat', subClass: 'alcohol_secondary', sub: S.alcohol_secondary.smi, prod: 'C=CC', mech: 'E1', steps: ['Secondary cation, then loss of a beta proton.'], thomas: 'Slower than tertiary because the cation is less happy, but the same move.', trap: 'Primary alcohols dehydrate by E2 and need harsher heat.', roots: ['l2-carbocation'], booster: 'Alcohols, Ethers, & Epoxides' }),
  rx({ id: 'alc1_tscl', family: 'alcohols', name: 'Tosylation', reagent: 'TsCl', cond: 'pyridine', subClass: 'alcohol_primary', sub: S.alcohol_primary.smi, prod: 'CCCOS(=O)(=O)c1ccc(C)cc1', stereo: 'retention at carbon', mech: 'nucleophilic attack on sulfur', steps: ['The alcohol oxygen attacks sulfur; the C-O bond is never touched.'], thomas: 'Tosylate is a great leaving group you install without touching the carbon, so the stereocenter keeps its shape.', trap: 'Retention here, then inversion when a nucleophile later kicks the tosylate off.', roots: ['l2-arrows', 'l3-wedge'], booster: 'Alcohols, Ethers, & Epoxides' }),
  rx({ id: 'alc1_williamson', family: 'alcohols', name: 'Williamson ether synthesis', reagent: '1. NaH', cond: '2. CH3CH2CH2Br', subClass: 'alcohol_primary', sub: S.alcohol_primary.smi, prod: 'CCCOCCC', mech: 'acid-base then SN2', steps: ['NaH makes the alkoxide.', 'The alkoxide attacks a primary halide by SN2.'], thomas: 'Alkoxide plus primary halide is an ether. Use a tertiary halide and you get elimination instead.', trap: 'The halide must be primary or methyl.', roots: ['l2-arrows', 'l2-acidity'], booster: 'Alcohols, Ethers, & Epoxides' }),
  rx({ id: 'alc1_fischer', family: 'alcohols', name: 'Fischer esterification', reagent: 'CH3COOH', cond: 'H+ (cat.), heat', subClass: 'alcohol_primary', sub: S.alcohol_primary.smi, prod: 'CCCOC(C)=O', mech: 'acid-catalyzed acyl substitution', steps: ['Protonate the acid carbonyl.', 'The alcohol attacks, proton transfers, water leaves.'], thomas: 'Acid plus alcohol plus a little acid and heat is an ester. Reversible, so remove water to push it.', trap: 'The ester oxygen comes from the alcohol, not from the acid.', roots: ['l2-bully', 'l2-arrows'], booster: 'Alcohols, Ethers, & Epoxides' }),

  // ---------------- ALKYL HALIDES: SUBSTITUTION AND ELIMINATION ----------------
  rx({ id: 'hal1_nai', family: 'subelim', name: 'Finkelstein exchange', reagent: 'NaI', cond: 'acetone', subClass: 'halide_primary', sub: S.halide_primary.smi, prod: 'CCCI', mech: 'SN2', steps: ['Iodide attacks from the back; bromide leaves.'], thomas: 'Primary halide, good nucleophile, aprotic solvent: SN2 and nothing else.', trap: 'Acetone is aprotic; that is the SN2 tell.', roots: ['l2-arrows'], booster: 'Substitution & Elimination' }),
  rx({ id: 'hal1_nacn', family: 'subelim', name: 'Cyanide substitution', reagent: 'NaCN', cond: 'DMSO', subClass: 'halide_primary', sub: S.halide_primary.smi, prod: 'CCCC#N', mech: 'SN2', steps: ['Cyanide attacks the primary carbon by SN2.'], thomas: 'Cyanide adds one carbon. Count them.', trap: 'The product has one more carbon than the halide.', roots: ['l2-arrows', 'l1-skeletal'], booster: 'Substitution & Elimination' }),
  rx({ id: 'hal1_naoh', family: 'subelim', name: 'Hydroxide on a primary halide', reagent: 'NaOH', subClass: 'halide_primary', sub: S.halide_primary.smi, prod: 'CCCO', stereo: 'inversion', mech: 'SN2', steps: ['Hydroxide attacks from the back side.'], thomas: 'Strong small nucleophile on a primary carbon: attack, kick it off, attach.', trap: 'Same reagent on a tertiary halide eliminates.', roots: ['l2-arrows', 'l3-wedge'], booster: 'Substitution & Elimination' }),
  rx({ id: 'hal2_nai', family: 'subelim', name: 'Iodide on a secondary halide', reagent: 'NaI', cond: 'acetone', subClass: 'halide_secondary', sub: S.halide_secondary.smi, prod: 'CC(C)I', stereo: 'inversion', mech: 'SN2', steps: ['Backside attack inverts the center.'], thomas: 'Secondary is allowed for SN2 when the nucleophile is good and the solvent is aprotic.', trap: 'The reagent decides on a secondary carbon.', roots: ['l2-arrows', 'l3-wedge'], booster: 'Substitution & Elimination' }),
  rx({ id: 'hal2_naoet', family: 'subelim', name: 'Ethoxide on a secondary halide', reagent: 'NaOEt', cond: 'EtOH', subClass: 'halide_secondary', sub: S.halide_secondary.smi, prod: 'C=CC', regio: 'Zaitsev', mech: 'E2', steps: ['The base takes a beta hydrogen anti to the bromide as the bromide leaves.'], thomas: 'Naioet is a strong small base, so on a secondary carbon she eliminates, Zaitsev.', trap: 'Strong base on secondary is E2, not SN2.', roots: ['l3-newman', 'l2-acidity'], booster: 'Substitution & Elimination' }),
  rx({ id: 'hal3_h2o', family: 'subelim', name: 'Solvolysis of a tertiary halide', reagent: 'H2O', cond: 'heat', subClass: 'halide_tertiary', sub: S.halide_tertiary.smi, prod: 'CC(C)(C)O', prodNote: 'plus some 2-methylpropene by E1', stereo: 'racemic if a center forms', mech: 'SN1 with E1', steps: ['Bromide leaves on its own to give the tertiary cation.', 'Water attacks the flat cation from either face.'], thomas: 'Weak nucleophile, protic solvent, tertiary carbon: SN1 and E1 travel together.', trap: 'A flat carbocation means racemization, not inversion.', roots: ['l2-carbocation', 'l1-geometry'], booster: 'Substitution & Elimination' }),
  rx({ id: 'hal3_meoh', family: 'subelim', name: 'Methanolysis of a tertiary halide', reagent: 'CH3OH', subClass: 'halide_tertiary', sub: S.halide_tertiary.smi, prod: 'COC(C)(C)C', mech: 'SN1', steps: ['Leave, then the solvent attacks the cation.'], thomas: 'Tertiary never SN2. The bromide leaves first and methanol fills the hole.', trap: 'Rate depends only on the substrate, not the nucleophile.', roots: ['l2-carbocation'], booster: 'Substitution & Elimination' }),
  rx({ id: 'hal3_tbuok', family: 'subelim', name: 'Bulky base, Hofmann product', reagent: 'KOtBu', cond: 'tBuOH', subClass: 'halide_tertiary_b', sub: S.halide_tertiary_b.smi, prod: 'C=C(C)CC', regio: 'Hofmann: the less substituted alkene', mech: 'E2', steps: ['The bulky base cannot reach the crowded hydrogen, so it takes the exposed methyl hydrogen.'], thomas: 'Potassium tert-butoxide is too bulky to reach the crowded spot, so it is forced to the less crowded one and gives Hofmann.', trap: 'Same substrate with NaOEt gives the Zaitsev alkene.', roots: ['l3-newman', 'l2-carbocation'], booster: 'Substitution & Elimination' }),
  rx({ id: 'hal3_naoet', family: 'subelim', name: 'Small base, Zaitsev product', reagent: 'NaOEt', cond: 'EtOH', subClass: 'halide_tertiary_b', sub: S.halide_tertiary_b.smi, prod: 'CC=C(C)C', regio: 'Zaitsev: the more substituted alkene', mech: 'E2', steps: ['The small base slips in and takes the hydrogen that gives the more substituted alkene.'], thomas: 'A small base like sodium ethoxide slips into the crowded spot and takes the Zaitsev hydrogen.', trap: 'Bulky base flips it to Hofmann.', roots: ['l3-newman', 'l2-carbocation'], booster: 'Substitution & Elimination' }),
  rx({ id: 'hal1_azide', family: 'subelim', name: 'Azide route to a primary amine', reagent: '1. NaN3', cond: '2. LiAlH4', subClass: 'halide_primary', sub: S.halide_primary.smi, prod: 'CCCN', mech: 'SN2 then reduction', steps: ['Azide substitutes by SN2.', 'Hydride reduces the azide to the amine.'], thomas: 'Azide is the clean way to a primary amine; ammonia would keep alkylating.', trap: 'Direct NH3 gives a mixture of amines.', roots: ['l2-arrows'], booster: 'Substitution & Elimination' }),
  rx({ id: 'hal1_gabriel', family: 'subelim', name: 'Gabriel synthesis', reagent: '1. potassium phthalimide', cond: '2. NH2NH2', subClass: 'halide_primary', sub: S.halide_primary.smi, prod: 'CCCN', mech: 'SN2 then hydrazinolysis', steps: ['Phthalimide anion substitutes by SN2.', 'Hydrazine releases the primary amine.'], thomas: 'Gabriel makes primary amines only, and only from primary halides.', trap: 'No secondary or tertiary amines from Gabriel.', roots: ['l2-arrows'], booster: 'Substitution & Elimination' }),

  // ---------------- ALDEHYDES AND KETONES ----------------
  rx({ id: 'ald_nabh4', family: 'carbonyl', name: 'Borohydride reduction of an aldehyde', reagent: 'NaBH4', cond: 'CH3OH', subClass: 'aldehyde', sub: S.aldehyde.smi, prod: 'CCCO', mech: 'nucleophilic addition of hydride', steps: ['Hydride attacks the carbonyl carbon.', 'The alkoxide picks up a proton.'], thomas: 'NaBH4 is weak: aldehydes and ketones only.', trap: 'It will not touch an ester or an acid.', roots: ['l2-bully', 'l2-arrows'], booster: 'Ketones & Aldehydes' }),
  rx({ id: 'ald_lah', family: 'carbonyl', name: 'LiAlH4 reduction of an aldehyde', reagent: '1. LiAlH4', cond: '2. H2O', subClass: 'aldehyde', sub: S.aldehyde.smi, prod: 'CCCO', mech: 'nucleophilic addition of hydride', steps: ['Hydride attacks; water workup gives the alcohol.'], thomas: 'LiAlH4 is strong; it does everything NaBH4 does and more.', trap: 'Never mix LiAlH4 with water before the workup.', roots: ['l2-bully', 'l2-arrows'], booster: 'Ketones & Aldehydes' }),
  rx({ id: 'ald_grignard', family: 'carbonyl', name: 'Grignard on an aldehyde', reagent: '1. CH3MgBr', cond: '2. H3O+', subClass: 'aldehyde', sub: S.aldehyde.smi, prod: 'CCC(C)O', mech: 'nucleophilic addition', steps: ['The carbon on magnesium attacks the carbonyl carbon.', 'Acid workup protonates the alkoxide.'], thomas: 'Green yard: R attacks the carbonyl carbon, and MgBr is never in the product.', trap: 'Aldehyde gives a secondary alcohol; ketone gives tertiary.', roots: ['l2-bully', 'l2-arrows'], booster: 'Ketones & Aldehydes' }),
  rx({ id: 'ald_hcn', family: 'carbonyl', name: 'Cyanohydrin formation', reagent: 'HCN', cond: 'KCN (cat.)', subClass: 'aldehyde', sub: S.aldehyde.smi, prod: 'CCC(O)C#N', mech: 'nucleophilic addition', steps: ['Cyanide attacks the carbonyl carbon.', 'The alkoxide takes a proton from HCN.'], thomas: 'OH and CN end up on the same carbon, one carbon longer.', trap: 'Adds a carbon; count it.', roots: ['l2-arrows', 'l1-skeletal'], booster: 'Ketones & Aldehydes' }),
  rx({ id: 'ald_imine', family: 'carbonyl', name: 'Imine formation', reagent: 'CH3NH2', cond: 'H+ (pH 4 to 5)', subClass: 'aldehyde', sub: S.aldehyde.smi, prod: 'CCC=NC', mech: 'addition then dehydration', steps: ['The primary amine adds to the carbonyl.', 'Water leaves and the N-H proton is lost to make C=N.'], thomas: 'I-mine: a primary amine takes the double bond as C=N.', trap: 'A secondary amine cannot lose that N-H, so it makes an enamine.', roots: ['l2-arrows', 'l1-charge'], booster: 'Ketones & Aldehydes' }),
  rx({ id: 'ald_enamine', family: 'carbonyl', name: 'Enamine formation', reagent: '(CH3)2NH', cond: 'H+ (pH 4 to 5)', subClass: 'aldehyde', sub: S.aldehyde.smi, prod: 'CC=CN(C)C', mech: 'addition then dehydration', steps: ['The secondary amine adds and water leaves.', 'With no N-H left, an alpha C-H is lost and the double bond sits next to nitrogen.'], thomas: 'Secondary amine, no N-H to give up, so the double bond slides next door: an enamine.', trap: 'A tertiary amine gives no reaction at all.', roots: ['l2-arrows', 'l1-charge'], booster: 'Ketones & Aldehydes' }),
  rx({ id: 'ald_acetal', family: 'carbonyl', name: 'Acetal formation', reagent: '2 CH3OH', cond: 'H+ (cat.)', subClass: 'aldehyde', sub: S.aldehyde.smi, prod: 'CCC(OC)OC', mech: 'acid-catalyzed addition, twice', steps: ['One alcohol adds to make a hemiacetal.', 'Acid turns the OH into water; a second alcohol replaces it.'], thomas: 'An acetal is a phone case on the carbonyl. Only aqueous acid takes it off.', trap: 'Acetals survive base, Grignards and hydrides; that is why they are protecting groups.', roots: ['l2-arrows', 'l2-bully'], booster: 'Ketones & Aldehydes' }),
  rx({ id: 'ald_wittig', family: 'carbonyl', name: 'Wittig reaction', reagent: 'Ph3P=CH2', subClass: 'aldehyde', sub: S.aldehyde.smi, prod: 'CCC=C', mech: 'ylide addition, oxaphosphetane', steps: ['The ylide carbon attacks the carbonyl.', 'A four-membered ring forms and falls apart into the alkene and Ph3P=O.'], thomas: 'Wittig turns C=O into C=C, and the new double bond is exactly where the carbonyl was.', trap: 'Triphenylphosphine oxide is the byproduct, never in the answer.', roots: ['l2-arrows'], booster: 'Ketones & Aldehydes' }),
  rx({ id: 'ald_clemmensen', family: 'carbonyl', name: 'Clemmensen reduction', reagent: 'Zn(Hg)', cond: 'HCl', subClass: 'aldehyde', sub: S.aldehyde.smi, prod: 'CCC', mech: 'reduction to CH2', steps: ['The carbonyl carbon ends up as CH2.'], thomas: 'The executioners: Clemmensen in acid, Wolff-Kishner in base, both erase the carbonyl.', trap: 'This removes the oxygen entirely; NaBH4 only reduces to the alcohol.', roots: ['l1-groups'], booster: 'Ketones & Aldehydes' }),
  rx({ id: 'ald_wolff', family: 'carbonyl', name: 'Wolff-Kishner reduction', reagent: 'NH2NH2', cond: 'KOH, heat', subClass: 'aldehyde', sub: S.aldehyde.smi, prod: 'CCC', mech: 'hydrazone then loss of N2', steps: ['Hydrazine makes the hydrazone.', 'Base and heat drive off N2, leaving CH2.'], thomas: 'The basic executioner. Same outcome as Clemmensen, opposite conditions.', trap: 'Choose it when the molecule cannot survive acid.', roots: ['l1-groups'], booster: 'Ketones & Aldehydes' }),
  rx({ id: 'ald_jones', family: 'carbonyl', name: 'Oxidation of an aldehyde', reagent: 'CrO3, H2SO4', cond: 'or Ag2O, or KMnO4', subClass: 'aldehyde', sub: S.aldehyde.smi, prod: 'CCC(=O)O', mech: 'oxidation', steps: ['The aldehyde C-H is oxidized to C-OH.'], thomas: 'Aldehydes oxidize easily; ketones do not, because they have no H on the carbonyl carbon.', trap: 'Tollens (Ag2O) oxidizes aldehydes only, which is the silver mirror test.', roots: ['l1-groups'], booster: 'Ketones & Aldehydes' }),
  rx({ id: 'ket_nabh4', family: 'carbonyl', name: 'Borohydride reduction of a ketone', reagent: 'NaBH4', cond: 'CH3OH', subClass: 'ketone', sub: S.ketone.smi, prod: 'CCC(C)O', mech: 'nucleophilic addition of hydride', steps: ['Hydride attacks the carbonyl carbon; the alkoxide is protonated.'], thomas: 'Ketone to secondary alcohol.', trap: 'A new stereocenter forms as a racemic mixture.', roots: ['l2-bully', 'l3-isomers'], booster: 'Ketones & Aldehydes' }),
  rx({ id: 'ket_grignard', family: 'carbonyl', name: 'Grignard on a ketone', reagent: '1. CH3MgBr', cond: '2. H3O+', subClass: 'ketone', sub: S.ketone.smi, prod: 'CCC(C)(C)O', mech: 'nucleophilic addition', steps: ['The Grignard carbon attacks the carbonyl; workup gives the tertiary alcohol.'], thomas: 'Ketone plus Grignard is a tertiary alcohol, always.', trap: 'Grignards are destroyed by any acidic proton in the molecule; protect alcohols first.', roots: ['l2-bully', 'l2-acidity'], booster: 'Ketones & Aldehydes' }),
  rx({ id: 'ket_ketal', family: 'carbonyl', name: 'Ketal formation', reagent: '2 CH3OH', cond: 'H+ (cat.)', subClass: 'ketone', sub: S.ketone.smi, prod: 'CCC(C)(OC)OC', mech: 'acid-catalyzed addition, twice', steps: ['Hemiketal, then the second alcohol replaces water.'], thomas: 'Same phone case, on a ketone it is called a ketal.', trap: 'Removed only by aqueous acid.', roots: ['l2-arrows'], booster: 'Ketones & Aldehydes' }),
  rx({ id: 'ket_imine', family: 'carbonyl', name: 'Ketimine formation', reagent: 'CH3NH2', cond: 'H+ (pH 4 to 5)', subClass: 'ketone', sub: S.ketone.smi, prod: 'CCC(C)=NC', mech: 'addition then dehydration', steps: ['Primary amine adds, water leaves, C=N forms.'], thomas: 'Primary makes imine, on a ketone too.', trap: 'Too acidic and the amine is protonated and cannot attack; pH 4 to 5 is the sweet spot.', roots: ['l2-arrows', 'l2-acidity'], booster: 'Ketones & Aldehydes' }),
  rx({ id: 'ket_wittig', family: 'carbonyl', name: 'Wittig on a ketone', reagent: 'Ph3P=CH2', subClass: 'ketone', sub: S.ketone.smi, prod: 'C=C(C)CC', mech: 'ylide addition', steps: ['The ylide carbon replaces the oxygen with CH2.'], thomas: 'Carbonyl carbon becomes the alkene carbon.', trap: 'The alkene is exactly at the old carbonyl, never moved.', roots: ['l2-arrows'], booster: 'Ketones & Aldehydes' }),
  rx({ id: 'ket_hcn', family: 'carbonyl', name: 'Cyanohydrin from a ketone', reagent: 'HCN', cond: 'KCN (cat.)', subClass: 'ketone', sub: S.ketone.smi, prod: 'CCC(C)(O)C#N', mech: 'nucleophilic addition', steps: ['Cyanide attacks; the alkoxide is protonated.'], thomas: 'Adds one carbon and an OH on the same carbon.', trap: 'Hindered ketones react poorly.', roots: ['l2-arrows'], booster: 'Ketones & Aldehydes' }),
  rx({ id: 'ket_red_amination', family: 'carbonyl', name: 'Reductive amination', reagent: 'CH3NH2', cond: 'NaBH3CN, pH 4 to 5', subClass: 'ketone', sub: S.ketone.smi, prod: 'CCC(C)NC', mech: 'imine then reduction', steps: ['The imine forms.', 'The mild hydride reduces C=N to C-N.'], thomas: 'Make the imine and reduce it in the same pot: a secondary amine in one step.', trap: 'NaBH3CN is mild enough to leave the ketone alone until the imine forms.', roots: ['l2-arrows'], booster: 'Ketones & Aldehydes' }),

  // ---------------- ACIDS AND DERIVATIVES ----------------
  rx({ id: 'acid_socl2', family: 'acids', name: 'Acid chloride formation', reagent: 'SOCl2', subClass: 'acid', sub: S.acid.smi, prod: 'CC(=O)Cl', mech: 'acyl substitution', steps: ['The acid OH is replaced by Cl.'], thomas: 'SOCl2 turns the acid into the diva of the family, the acid chloride.', trap: 'This is activation: the acid chloride can then reach every other derivative.', roots: ['l1-groups', 'l2-bully'], booster: 'Carboxylic Acid Derivatives' }),
  rx({ id: 'acid_fischer', family: 'acids', name: 'Fischer esterification of the acid', reagent: 'CH3CH2OH', cond: 'H+ (cat.), heat', subClass: 'acid', sub: S.acid.smi, prod: 'CCOC(C)=O', mech: 'acid-catalyzed acyl substitution', steps: ['Protonate the carbonyl, alcohol attacks, water leaves.'], thomas: 'Acid plus alcohol plus acid catalyst and heat is an ester.', trap: 'Reversible; excess alcohol or removing water pushes it forward.', roots: ['l2-arrows', 'l2-bully'], booster: 'Carboxylic Acid Derivatives' }),
  rx({ id: 'acid_lah', family: 'acids', name: 'LiAlH4 reduction of an acid', reagent: '1. LiAlH4', cond: '2. H2O', subClass: 'acid', sub: S.acid.smi, prod: 'CCO', mech: 'hydride reduction, twice', steps: ['Hydride reduces the acid all the way to the primary alcohol.'], thomas: 'LiAlH4 takes an acid all the way down to the alcohol. NaBH4 will not touch it.', trap: 'No stopping at the aldehyde with LiAlH4.', roots: ['l2-bully'], booster: 'Carboxylic Acid Derivatives' }),
  rx({ id: 'acid_amide', family: 'acids', name: 'Amide from an acid and an amine', reagent: 'CH3NH2', cond: 'heat', subClass: 'acid', sub: S.acid.smi, prod: 'CNC(C)=O', mech: 'acid-base then dehydration', steps: ['The amine first takes the acid proton to make a salt.', 'Heat drives out water to form the amide.'], thomas: 'First it is acid-base chemistry; only heat turns the salt into the amide.', trap: 'Without heat you only have the ammonium carboxylate.', roots: ['l2-acidity'], booster: 'Carboxylic Acid Derivatives' }),
  rx({ id: 'ester_saponification', family: 'acids', name: 'Saponification', reagent: 'NaOH', cond: 'H2O, heat', subClass: 'ester', sub: S.ester.smi, prod: 'CC(=O)[O-]', prodNote: 'the carboxylate salt plus methanol; acid workup gives the acid', mech: 'nucleophilic acyl substitution', steps: ['Hydroxide attacks the carbonyl.', 'Methoxide leaves.', 'The acid formed hands its proton to methoxide, which makes the step irreversible.'], thomas: 'Base cuts the ester and keeps the acid as its salt, so it cannot go back.', trap: 'The product in base is the carboxylate, not the acid, until you add acid.', roots: ['l2-arrows', 'l2-acidity'], booster: 'Carboxylic Acid Derivatives' }),
  rx({ id: 'ester_hydrolysis_acid', family: 'acids', name: 'Acid-catalyzed ester hydrolysis', reagent: 'H3O+', cond: 'heat', subClass: 'ester', sub: S.ester.smi, prod: 'CC(=O)O', prodNote: 'plus methanol', mech: 'acid-catalyzed acyl substitution', steps: ['Fischer esterification run backward with excess water.'], thomas: 'Same mechanism as making the ester, just read in reverse with a lot of water.', trap: 'Reversible, unlike saponification.', roots: ['l2-arrows'], booster: 'Carboxylic Acid Derivatives' }),
  rx({ id: 'ester_lah', family: 'acids', name: 'LiAlH4 reduction of an ester', reagent: '1. LiAlH4', cond: '2. H2O', subClass: 'ester', sub: S.ester.smi, prod: 'CCO', prodNote: 'plus methanol from the alkoxy side', mech: 'hydride reduction, twice', steps: ['Hydride attacks, methoxide leaves to give the aldehyde, a second hydride gives the alcohol.'], thomas: 'An ester cut by LiAlH4 gives two alcohols.', trap: 'Both halves come out as alcohols.', roots: ['l2-bully'], booster: 'Carboxylic Acid Derivatives' }),
  rx({ id: 'ester_dibal', family: 'acids', name: 'DIBAL-H on an ester', reagent: 'DIBAL-H (1 equiv)', cond: '-78 C, then H2O', subClass: 'ester', sub: S.ester.smi, prod: 'CC=O', mech: 'hydride reduction, once', steps: ['One hydride adds; the tetrahedral intermediate survives the cold until workup.'], thomas: 'DIBAL, cold, one equivalent: it stops at the aldehyde.', trap: 'Warm it or add more and you get the alcohol.', roots: ['l2-bully'], booster: 'Carboxylic Acid Derivatives' }),
  rx({ id: 'ester_grignard', family: 'acids', name: 'Two Grignards on an ester', reagent: '1. 2 CH3MgBr', cond: '2. H3O+', subClass: 'ester', sub: S.ester.smi, prod: 'CC(C)(C)O', mech: 'acyl substitution then addition', steps: ['The first Grignard kicks out methoxide to give a ketone.', 'The second adds to the ketone.'], thomas: 'The Grignard hits twice: the ester becomes a tertiary alcohol with two identical R groups.', trap: 'You cannot stop at the ketone with a Grignard.', roots: ['l2-arrows'], booster: 'Carboxylic Acid Derivatives' }),
  rx({ id: 'amide_lah', family: 'acids', name: 'LiAlH4 reduction of an amide', reagent: '1. LiAlH4', cond: '2. H2O', subClass: 'amide', sub: S.amide.smi, prod: 'CCN', mech: 'hydride reduction, nitrogen stays', steps: ['Hydride reduces C=O to CH2 and the nitrogen stays attached.'], thomas: 'The amide keeps its nitrogen and becomes an amine. The oxygen is the one that leaves.', trap: 'Not an alcohol; the N is the better leaving group only after the carbonyl is gone.', roots: ['l1-groups'], booster: 'Carboxylic Acid Derivatives' }),
  rx({ id: 'amide_hydrolysis', family: 'acids', name: 'Amide hydrolysis', reagent: 'H3O+', cond: 'heat, prolonged', subClass: 'amide', sub: S.amide.smi, prod: 'CC(=O)O', prodNote: 'plus ammonium', mech: 'acid-catalyzed acyl substitution', steps: ['Water attacks the protonated carbonyl; ammonia leaves as ammonium.'], thomas: 'Amides are the bottom of the ladder, so they need heat and time to hydrolyze.', trap: 'Least reactive derivative; harsh conditions.', roots: ['l2-resonance'], booster: 'Carboxylic Acid Derivatives' }),
  rx({ id: 'nitrile_lah', family: 'acids', name: 'LiAlH4 reduction of a nitrile', reagent: '1. LiAlH4', cond: '2. H2O', subClass: 'nitrile', sub: S.nitrile.smi, prod: 'CCCN', mech: 'hydride reduction, twice', steps: ['Two hydrides add to the triple bond.'], thomas: 'A nitrile becomes a primary amine with the same carbon count.', trap: 'The CN carbon becomes the CH2 of the amine.', roots: ['l1-skeletal'], booster: 'Carboxylic Acid Derivatives' }),
  rx({ id: 'nitrile_dibal', family: 'acids', name: 'DIBAL-H on a nitrile', reagent: 'DIBAL-H (1 equiv)', cond: '-78 C, then H2O', subClass: 'nitrile', sub: S.nitrile.smi, prod: 'CCC=O', mech: 'hydride reduction, once, then hydrolysis', steps: ['One hydride gives an imine; water hydrolyzes it to the aldehyde.'], thomas: 'DIBAL stops halfway again: the nitrile becomes an aldehyde.', trap: 'The nitrogen is lost in the workup.', roots: ['l1-groups'], booster: 'Carboxylic Acid Derivatives' }),
  rx({ id: 'acyl_h2o', family: 'acids', name: 'Acid chloride hydrolysis', reagent: 'H2O', subClass: 'acid_chloride', sub: S.acid_chloride.smi, prod: 'CC(=O)O', mech: 'nucleophilic acyl substitution', steps: ['Water attacks, chloride leaves, no catalyst needed.'], thomas: 'The acid chloride is so reactive plain water takes it apart.', trap: 'Fastest hydrolysis on the ladder.', roots: ['l2-bully'], booster: 'Carboxylic Acid Derivatives' }),
  rx({ id: 'acyl_ester', family: 'acids', name: 'Ester from an acid chloride', reagent: 'CH3CH2OH', cond: 'pyridine', subClass: 'acid_chloride', sub: S.acid_chloride.smi, prod: 'CCOC(C)=O', mech: 'nucleophilic acyl substitution', steps: ['The alcohol attacks, chloride leaves, pyridine mops up HCl.'], thomas: 'Down the ladder, easy: acid chloride to ester.', trap: 'Pyridine is there to catch the HCl, not to react.', roots: ['l2-arrows'], booster: 'Carboxylic Acid Derivatives' }),
  rx({ id: 'acyl_amide', family: 'acids', name: 'Amide from an acid chloride', reagent: '2 CH3NH2', subClass: 'acid_chloride', sub: S.acid_chloride.smi, prod: 'CNC(C)=O', mech: 'nucleophilic acyl substitution', steps: ['The amine attacks, chloride leaves, a second amine takes the HCl.'], thomas: 'Two equivalents of amine: one reacts, one takes the acid.', trap: 'With one equivalent half the amine is lost as its salt.', roots: ['l2-arrows'], booster: 'Carboxylic Acid Derivatives' }),
  rx({ id: 'acyl_bulky_hydride', family: 'acids', name: 'Bulky hydride to the aldehyde', reagent: 'LiAlH(OtBu)3', cond: 'cold', subClass: 'acid_chloride', sub: S.acid_chloride.smi, prod: 'CC=O', mech: 'acyl substitution, one hydride', steps: ['A bulky hydride adds once and the aldehyde survives.'], thomas: 'Bulky and cold means it stops halfway.', trap: 'Plain LiAlH4 would go to the alcohol.', roots: ['l2-bully'], booster: 'Carboxylic Acid Derivatives' }),
  rx({ id: 'acyl_gilman', family: 'acids', name: 'Gilman reagent to a ketone', reagent: '(CH3)2CuLi', subClass: 'acid_chloride', sub: S.acid_chloride.smi, prod: 'CC(C)=O', mech: 'acyl substitution', steps: ['The soft cuprate substitutes chloride and stops at the ketone.'], thomas: 'Gilman is the polite Grignard: it stops at the ketone.', trap: 'A Grignard would add twice.', roots: ['l2-bully'], booster: 'Carboxylic Acid Derivatives' }),
  rx({ id: 'acyl_grignard_xs', family: 'acids', name: 'Excess Grignard on an acid chloride', reagent: '1. 2 CH3MgBr', cond: '2. H3O+', subClass: 'acid_chloride', sub: S.acid_chloride.smi, prod: 'CC(C)(C)O', mech: 'acyl substitution then addition', steps: ['First Grignard makes the ketone; the second adds to it.'], thomas: 'Grignard overshoots: hit twice, tertiary alcohol.', trap: 'Same as the ester: two identical groups end up on the carbinol carbon.', roots: ['l2-arrows'], booster: 'Carboxylic Acid Derivatives' }),

  // ---------------- ALPHA CARBON ----------------
  rx({ id: 'aldol', family: 'alpha', name: 'Aldol addition', reagent: 'NaOH', cond: 'H2O, cold', subClass: 'acetaldehyde', sub: S.acetaldehyde.smi, prod: 'CC(O)CC=O', mech: 'enolate addition', steps: ['Hydroxide makes an enolate from one aldehyde.', 'The enolate carbon attacks the carbonyl of a second aldehyde.', 'Protonation gives the beta-hydroxy aldehyde.'], thomas: 'The alpha carbon wakes up, attacks another carbonyl, and you get an alcohol beta to the carbonyl.', trap: 'Cold stops at the aldol; heat dehydrates to the enone.', roots: ['l2-acidity', 'l2-arrows'], booster: 'Enolate Reactions' }),
  rx({ id: 'aldol_condensation', family: 'alpha', name: 'Aldol condensation', reagent: 'NaOH', cond: 'H2O, heat', subClass: 'acetaldehyde', sub: S.acetaldehyde.smi, prod: 'C/C=C/C=O', mech: 'enolate addition then E1cB dehydration', steps: ['Aldol first.', 'Heat removes water to make the conjugated enone.'], thomas: 'Heat and the aldol loses water; the new double bond is conjugated to the carbonyl.', trap: 'The double bond forms between the alpha and beta carbons.', roots: ['l2-resonance', 'l2-arrows'], booster: 'Enolate Reactions' }),
  rx({ id: 'claisen', family: 'alpha', name: 'Claisen condensation', reagent: 'NaOEt', cond: 'EtOH, then mild acid', subClass: 'ethyl_acetate', sub: S.ethyl_acetate.smi, prod: 'CC(=O)CC(=O)OCC', mech: 'enolate acyl substitution', steps: ['Ethoxide makes an ester enolate.', 'It attacks a second ester; ethoxide leaves.', 'The beta-keto ester is deprotonated until the acid workup.'], thomas: 'Claisen: NaOEt with two esters gives a beta-keto ester, every time.', trap: 'Use the alkoxide that matches the ester or you swap the ester group.', roots: ['l2-acidity', 'l2-arrows'], booster: 'Enolate Reactions' }),
  rx({ id: 'michael', family: 'alpha', name: 'Michael addition', reagent: 'C=CC(C)=O (methyl vinyl ketone)', cond: 'NaOEt', subClass: 'diketone', sub: S.diketone.smi, prod: 'CC(=O)C(CCC(C)=O)C(C)=O', mech: 'conjugate addition', steps: ['The stabilized enolate forms.', 'It attacks the beta carbon of the enone, not the carbonyl.', 'Protonation at the alpha carbon.'], thomas: 'A soft, stabilized enolate goes for the far end of the enone: 1,4 not 1,2.', trap: 'Conjugate addition lands on the beta carbon.', roots: ['l2-resonance', 'l2-arrows'], booster: 'Enolate Reactions' }),
  rx({ id: 'enolate_alkylation', family: 'alpha', name: 'Enolate alkylation', reagent: '1. LDA, THF, -78 C', cond: '2. CH3I', subClass: 'acetone', sub: S.acetone.smi, prod: 'CCC(C)=O', mech: 'enolate SN2', steps: ['LDA takes an alpha proton completely.', 'The enolate carbon attacks methyl iodide by SN2.'], thomas: 'LDA makes the enolate all at once; then the alpha carbon does an SN2 on the halide.', trap: 'Primary or methyl halides only.', roots: ['l2-acidity', 'l2-arrows'], booster: 'Enolate Reactions' }),
  rx({ id: 'alpha_halogenation', family: 'alpha', name: 'Acid-catalyzed alpha bromination', reagent: 'Br2', cond: 'CH3COOH', subClass: 'acetone', sub: S.acetone.smi, prod: 'CC(=O)CBr', mech: 'enol attacks Br2', steps: ['Acid makes the enol.', 'The enol attacks bromine at the alpha carbon.'], thomas: 'The enol is a nucleophile at the alpha carbon; it grabs one bromine and stops.', trap: 'In base it keeps going (haloform); in acid it stops at one.', roots: ['l2-resonance'], booster: 'Enolate Reactions' }),
  rx({ id: 'decarboxylation', family: 'alpha', name: 'Decarboxylation of a beta-keto acid', reagent: 'heat', subClass: 'betaketoacid', sub: S.betaketoacid.smi, prod: 'CC(C)=O', prodNote: 'plus CO2', mech: 'cyclic six-membered transition state', steps: ['The carbonyl oxygen takes the acid proton as CO2 leaves.', 'The enol tautomerizes to the ketone.'], thomas: 'A carboxyl beta to a carbonyl falls off as CO2 with heat. That is the acetoacetic ester ending.', trap: 'Only beta-keto and malonic acids do this easily.', roots: ['l2-resonance'], booster: 'Enolate Reactions' }),

  // ---------------- AROMATICS ----------------
  rx({ id: 'eas_br', family: 'aromatic', name: 'Bromination of benzene', reagent: 'Br2', cond: 'FeBr3', subClass: 'benzene', sub: S.benzene.smi, prod: 'Brc1ccccc1', mech: 'electrophilic aromatic substitution', steps: ['FeBr3 makes Br2 electrophilic.', 'The ring attacks, forming the arenium ion.', 'Loss of H+ restores aromaticity.'], thomas: 'If you see a ring, think EAS. The ring attacks, then gives back a proton to stay aromatic.', trap: 'Substitution, not addition; the ring never loses aromaticity in the product.', roots: ['l2-resonance', 'l2-arrows'], booster: 'Aromaticity & Benzene Reactions' }),
  rx({ id: 'eas_no2', family: 'aromatic', name: 'Nitration', reagent: 'HNO3', cond: 'H2SO4', subClass: 'benzene', sub: S.benzene.smi, prod: '[O-][N+](=O)c1ccccc1', mech: 'electrophilic aromatic substitution', steps: ['Sulfuric acid makes the nitronium ion.', 'The ring attacks, then loses H+.'], thomas: 'Nitro is the door to aniline: nitrate, then reduce.', trap: 'The nitro group is meta directing for the next substitution.', roots: ['l2-resonance', 'l2-arrows'], booster: 'Aromaticity & Benzene Reactions' }),
  rx({ id: 'eas_so3', family: 'aromatic', name: 'Sulfonation', reagent: 'SO3', cond: 'H2SO4', subClass: 'benzene', sub: S.benzene.smi, prod: 'OS(=O)(=O)c1ccccc1', mech: 'electrophilic aromatic substitution', steps: ['SO3 is the electrophile; the ring attacks, then loses H+.'], thomas: 'Sulfonation is the reversible one: dilute acid and heat take it back off.', trap: 'Used as a blocking group because it can be removed.', roots: ['l2-resonance'], booster: 'Aromaticity & Benzene Reactions' }),
  rx({ id: 'eas_fc_alkyl', family: 'aromatic', name: 'Friedel-Crafts alkylation', reagent: 'CH3CH2CH2Cl', cond: 'AlCl3', subClass: 'benzene', sub: S.benzene.smi, prod: 'CC(C)c1ccccc1', prodNote: 'the propyl cation rearranges to isopropyl before it lands', regio: 'rearranged alkyl group', mech: 'electrophilic aromatic substitution, carbocation', steps: ['AlCl3 pulls the halide off to make a carbocation, which rearranges to secondary.', 'The ring attacks the cation.'], thomas: 'Friedel-Crafts alkylation runs through a carbocation, so it rearranges and it over-alkylates.', trap: 'Acylation does not rearrange; use it, then reduce, to get the straight chain.', roots: ['l2-carbocation', 'l2-resonance'], booster: 'Aromaticity & Benzene Reactions' }),
  rx({ id: 'eas_fc_acyl', family: 'aromatic', name: 'Friedel-Crafts acylation', reagent: 'CH3COCl', cond: 'AlCl3', subClass: 'benzene', sub: S.benzene.smi, prod: 'CC(=O)c1ccccc1', mech: 'electrophilic aromatic substitution, acylium', steps: ['AlCl3 makes the acylium ion, which cannot rearrange.', 'The ring attacks, then loses H+.'], thomas: 'The acylium is resonance-stabilized and never rearranges, and the ketone deactivates the ring so it stops at one.', trap: 'Neither Friedel-Crafts works on a strongly deactivated ring like nitrobenzene.', roots: ['l2-resonance'], booster: 'Aromaticity & Benzene Reactions' }),
  rx({ id: 'eas_anisole_no2', family: 'aromatic', name: 'Nitration of anisole', reagent: 'HNO3', cond: 'H2SO4', subClass: 'anisole', sub: S.anisole.smi, prod: 'COc1ccc([N+](=O)[O-])cc1', regio: 'para (and ortho); methoxy is an activating ortho/para director', mech: 'electrophilic aromatic substitution', steps: ['The methoxy lone pair donates by resonance, so the ring is rich at ortho and para.', 'The nitronium attacks para.'], thomas: 'LPOP: lone pair oxygen groups push electrons in and send the newcomer ortho or para.', trap: 'Para dominates ortho because of sterics, but both are ortho/para products.', roots: ['l2-resonance', 'l2-induction'], booster: 'Aromaticity & Benzene Reactions' }),
  rx({ id: 'eas_nitrobenzene_no2', family: 'aromatic', name: 'Nitration of nitrobenzene', reagent: 'HNO3', cond: 'H2SO4, heat', subClass: 'nitrobenzene', sub: S.nitrobenzene.smi, prod: '[O-][N+](=O)c1cccc([N+](=O)[O-])c1', regio: 'meta; nitro deactivates and directs meta', mech: 'electrophilic aromatic substitution', steps: ['The nitro group pulls density out of ortho and para, leaving meta as the least poor position.'], thomas: 'A withdrawer drains the party and shoves the newcomer to meta.', trap: 'Slow, needs heat; the ring is deactivated.', roots: ['l2-resonance', 'l2-induction'], booster: 'Aromaticity & Benzene Reactions' }),
  rx({ id: 'eas_chlorobenzene_br', family: 'aromatic', name: 'Bromination of chlorobenzene', reagent: 'Br2', cond: 'FeBr3', subClass: 'chlorobenzene', sub: S.chlorobenzene.smi, prod: 'Clc1ccc(Br)cc1', regio: 'ortho/para, but slower than benzene', mech: 'electrophilic aromatic substitution', steps: ['The chlorine lone pair directs ortho/para by resonance while its electronegativity slows the ring by induction.'], thomas: 'Halogens are the oddball: ortho/para directors, but deactivators. Say it three times.', trap: 'Direction and rate are two separate questions.', roots: ['l2-resonance', 'l2-induction'], booster: 'Aromaticity & Benzene Reactions' }),
  rx({ id: 'nitro_reduction', family: 'aromatic', name: 'Nitro reduction to aniline', reagent: 'Fe or Sn', cond: 'HCl; or H2, Pd', subClass: 'nitrobenzene', sub: S.nitrobenzene.smi, prod: 'Nc1ccccc1', mech: 'reduction', steps: ['The nitro group is reduced to the amine.'], thomas: 'Nitrate then reduce is how you put an NH2 on a ring.', trap: 'This flips the group from a meta director to an ortho/para director.', roots: ['l2-resonance'], booster: 'Aromaticity & Benzene Reactions' }),
  rx({ id: 'sandmeyer_br', family: 'aromatic', name: 'Sandmeyer bromination', reagent: '1. NaNO2, HCl, 0 C', cond: '2. CuBr', subClass: 'aniline', sub: S.aniline.smi, prod: 'Brc1ccccc1', mech: 'diazonium substitution', steps: ['Nitrous acid makes the diazonium salt.', 'Copper bromide swaps N2 for Br.'], thomas: 'Diazonium is the universal adapter: NH2 becomes almost anything.', trap: 'Keep it cold; diazonium salts fall apart when warm.', roots: ['l2-arrows'], booster: 'Aromaticity & Benzene Reactions' }),
  rx({ id: 'sandmeyer_cl', family: 'aromatic', name: 'Sandmeyer chlorination', reagent: '1. NaNO2, HCl, 0 C', cond: '2. CuCl', subClass: 'aniline', sub: S.aniline.smi, prod: 'Clc1ccccc1', mech: 'diazonium substitution', steps: ['Diazotize, then CuCl.'], thomas: 'Same adapter, different plug.', trap: 'CuCN gives the nitrile; H3PO2 removes the group entirely.', roots: ['l2-arrows'], booster: 'Aromaticity & Benzene Reactions' }),
  rx({ id: 'deamination', family: 'aromatic', name: 'Deamination through diazonium', reagent: '1. NaNO2, HCl, 0 C', cond: '2. H3PO2', subClass: 'aniline', sub: S.aniline.smi, prod: 'c1ccccc1', mech: 'diazonium reduction', steps: ['Diazotize, then hypophosphorous acid replaces N2 with H.'], thomas: 'Put the amine on to direct, then take it off. That is how you get patterns you cannot make directly.', trap: 'The NH2 was a tool, not part of the target.', roots: ['l2-resonance'], booster: 'Aromaticity & Benzene Reactions' }),
  rx({ id: 'toluene_nbs', family: 'aromatic', name: 'Benzylic bromination', reagent: 'NBS', cond: 'light or peroxide', subClass: 'toluene', sub: S.toluene.smi, prod: 'BrCc1ccccc1', mech: 'radical substitution', steps: ['A bromine radical takes the benzylic hydrogen because that radical is resonance-stabilized.', 'The benzylic radical takes Br from NBS.'], thomas: 'NBS plus light is a radical swap next door to the ring, not addition.', trap: 'Br2 with FeBr3 would go on the ring instead.', roots: ['l2-carbocation', 'l2-resonance'], booster: 'Free Radical & Diels Alder Cycloaddition Reactions' }),
  rx({ id: 'toluene_kmno4', family: 'aromatic', name: 'Side-chain oxidation', reagent: 'KMnO4', cond: 'hot', subClass: 'toluene', sub: S.toluene.smi, prod: 'OC(=O)c1ccccc1', mech: 'benzylic oxidation', steps: ['Any alkyl side chain with a benzylic H burns down to COOH.'], thomas: 'Hot permanganate turns any alkyl side chain into a carboxylic acid; the ring survives.', trap: 'No benzylic hydrogen (tert-butyl) means no reaction.', roots: ['l1-groups'], booster: 'Aromaticity & Benzene Reactions' }),
  rx({ id: 'toluene_br', family: 'aromatic', name: 'Bromination of toluene', reagent: 'Br2', cond: 'FeBr3', subClass: 'toluene', sub: S.toluene.smi, prod: 'Cc1ccc(Br)cc1', regio: 'ortho/para; para shown', mech: 'electrophilic aromatic substitution', steps: ['Methyl donates a little; the ring is activated at ortho and para.'], thomas: 'Alkyl groups are mild hype men: ortho/para, a bit faster than benzene.', trap: 'Same reagent with light instead of FeBr3 goes to the side chain.', roots: ['l2-resonance'], booster: 'Aromaticity & Benzene Reactions' }),

  // ---------------- RADICALS AND PERICYCLIC ----------------
  rx({ id: 'radical_br2', family: 'radical', name: 'Radical bromination of an alkane', reagent: 'Br2', cond: 'light', subClass: 'alkane', sub: S.alkane.smi, prod: 'CC(C)(C)Br', regio: 'tertiary hydrogen, selective', mech: 'radical chain', steps: ['Light splits Br2 (initiation).', 'A bromine radical takes the tertiary H, the weakest.', 'The tertiary radical takes Br from Br2 (propagation).'], thomas: 'When you see light, think radicals. Bromine is picky and takes the tertiary H.', trap: 'Chlorine is unselective and gives a mixture.', roots: ['l2-carbocation'], booster: 'Free Radical & Diels Alder Cycloaddition Reactions' }),
  rx({ id: 'radical_cl2', family: 'radical', name: 'Radical chlorination of an alkane', reagent: 'Cl2', cond: 'light', subClass: 'alkane', sub: S.alkane.smi, prod: 'CC(C)CCl', prodNote: 'the primary chloride is the major product by count: nine primary hydrogens outweigh the one tertiary', regio: 'statistical mixture, primary major', mech: 'radical chain', steps: ['Chlorine radicals are unselective, so the nine primary hydrogens win on numbers.'], thomas: 'Chlorine does not care which H it takes, so count the hydrogens.', trap: 'Bromine gives the tertiary product; chlorine gives the mixture.', roots: ['l1-skeletal', 'l2-carbocation'], booster: 'Free Radical & Diels Alder Cycloaddition Reactions' }),
  rx({ id: 'diels_alder', family: 'radical', name: 'Diels-Alder cycloaddition', reagent: 'C=CC=O (acrolein)', cond: 'heat', subClass: 'diene', sub: S.diene.smi, prod: 'O=CC1CCC=CC1', mech: 'concerted [4+2] cycloaddition', steps: ['The s-cis diene and the electron-poor dienophile meet.', 'Three arrows move at once: two new sigma bonds, one new pi bond in the ring.'], thomas: 'Diels-Alder is three arrows every time, and the diene has to be s-cis.', trap: 'The new double bond sits between the two middle carbons of the old diene.', roots: ['l2-arrows', 'l1-unsat'], booster: 'Free Radical & Diels Alder Cycloaddition Reactions' }),
  rx({ id: 'diene_h2', family: 'radical', name: 'Full hydrogenation of a diene', reagent: 'H2 (excess)', cond: 'Pt', subClass: 'diene', sub: S.diene.smi, prod: 'CCCC', mech: 'catalytic surface addition', steps: ['Both pi bonds take H2.'], thomas: 'Two pi bonds, two H2, one alkane.', trap: 'Excess hydrogen means both go.', roots: ['l1-unsat'], booster: 'Free Radical & Diels Alder Cycloaddition Reactions' }),

  // ---------------- EPOXIDES ----------------
  rx({ id: 'epoxide_acid', family: 'ethers', name: 'Acidic epoxide opening', reagent: 'H3O+', subClass: 'epoxide', sub: S.epoxide.smi, prod: 'CC(O)CO', prodNote: 'the nucleophile attacks the more substituted carbon; with water both ends give the same diol', regio: 'more substituted carbon', stereo: 'anti', mech: 'protonated epoxide, SN1-like', steps: ['Protonate the epoxide oxygen.', 'The nucleophile attacks the more substituted carbon, which carries more positive character.'], thomas: 'Acid on an epoxide: protonate, then the nucleophile goes to the more substituted carbon, from the back.', trap: 'Base goes to the less substituted carbon instead.', roots: ['l2-carbocation', 'l2-arrows'], booster: 'Alcohols, Ethers, & Epoxides' }),
  rx({ id: 'epoxide_base', family: 'ethers', name: 'Basic epoxide opening', reagent: 'NaOCH3', cond: 'CH3OH', subClass: 'epoxide', sub: S.epoxide.smi, prod: 'COCC(C)O', regio: 'less substituted carbon', stereo: 'anti, inversion', mech: 'SN2', steps: ['The alkoxide attacks the less hindered carbon by SN2, opening the ring.'], thomas: 'A strong nucleophile treats the epoxide like any SN2: the open end.', trap: 'Regiochemistry flips between acid and base.', roots: ['l2-arrows'], booster: 'Alcohols, Ethers, & Epoxides' }),
  rx({ id: 'epoxide_grignard', family: 'ethers', name: 'Grignard opening of an epoxide', reagent: '1. CH3MgBr', cond: '2. H3O+', subClass: 'epoxide', sub: S.epoxide.smi, prod: 'CCC(C)O', regio: 'less substituted carbon', mech: 'SN2', steps: ['The carbanion attacks the less hindered carbon; the alkoxide is protonated on workup.'], thomas: 'Grignard plus epoxide extends the chain by two carbons and leaves an alcohol behind.', trap: 'Attack at the CH2, so the OH ends up on the more substituted carbon.', roots: ['l2-arrows', 'l1-skeletal'], booster: 'Alcohols, Ethers, & Epoxides' })
];

export const FAMILIES = ['alkenes', 'alkynes', 'alcohols', 'subelim', 'carbonyl', 'acids', 'alpha', 'aromatic', 'radical', 'ethers'];
export function byFamily(f){ return REACTIONS.filter(r => r.family === f); }
export function find(id){ return REACTIONS.find(r => r.id === id) || null; }
/** Reactions on the same substrate class with a different product: the honest distractors. */
export function siblings(r){ return REACTIONS.filter(x => x.id !== r.id && x.subClass === r.subClass && x.prod !== r.prod); }
/** Every SMILES in the table, for the render check. */
export function allSmiles(){ const s = new Set(); for (const r of REACTIONS){ s.add(r.sub); s.add(r.prod); } for (const k in SUBSTRATES) s.add(SUBSTRATES[k].smi); return [...s]; }
