#!/usr/bin/env node
'use strict';
/* Build the QR formats pool.
   Reads   scripts/qr-formats/src/{qc,ds,di,aw}.js  (authored items)
   Checks  every item (schema + exact recomputation of the key) and set gates
   Writes  shared/qr-formats-bank.js    (browser + Node: QR_FORMATS_DATA)
           shared/qr-formats-bank.json  (same data for other tools)
   Run:    node scripts/qr-formats/build.js          (fails on any problem)
           node scripts/qr-formats/build.js --check  (verify only, write nothing)
           node scripts/qr-formats/build.js --only qc   (verify one format, write nothing) */
const fs = require('fs');
const path = require('path');
const { verifyItem, setReport, orderOptions } = require('./lib/check.js');
const Figures = require('../../shared/qr-figures.js');

const ROOT = path.join(__dirname, '..', '..');
const SKILL = { qc: 'qc-compare', ds: 'ds-format', di: 'data-figs', aw: 'applied-wp' };
const LABEL = { qc: 'Quantitative Comparison', ds: 'Data Sufficiency', di: 'Data Interpretation (figures)', aw: 'Applied Word Problems' };

function load() {
  const items = [];
  for (const f of ['qc', 'ds', 'di', 'aw']) {
    const p = path.join(__dirname, 'src', f + '.js');
    if (!fs.existsSync(p)) continue;
    delete require.cache[require.resolve(p)];
    require(p).forEach((it) => items.push(it));
  }
  return items;
}

function main() {
  const checkOnly = process.argv.includes('--check');
  const oi = process.argv.indexOf('--only');
  const only = oi > 0 ? process.argv[oi + 1] : null;
  const items = load().filter((it) => !only || it.format === only);
  let bad = 0;
  items.forEach((it) => {
    const errs = verifyItem(it, Figures);
    if (errs.length) { bad++; console.log('FAIL ' + (it.id || '?') + ': ' + errs.join(' | ')); }
  });
  const rep = setReport(items);
  rep.problems.forEach((p) => console.log('SET  ' + p));
  console.log(JSON.stringify(rep.byFormat));
  if (bad || rep.problems.length) { console.log(`\n${bad} item(s) failing, ${rep.problems.length} set problem(s).`); process.exit(1); }
  console.log(`\nAll ${items.length} items verified.`);
  if (checkOnly || only) return;

  const out = items.map((it) => {
    const o = orderOptions(it);
    const diag = {};
    if (it.diag) for (const [k, v] of Object.entries(it.diag)) {
      const idx = (it.format === 'qc' || it.format === 'ds') ? 'ABCDE'.indexOf(k) : o.opts.indexOf(k);
      if (idx >= 0) diag[idx] = v;
    }
    const rec = { id: it.id, format: it.format, skill: SKILL[it.format], topic: it.topic, diff: it.diff, stem: it.stem };
    if (it.colA) { rec.colA = it.colA; rec.colB = it.colB; }
    if (it.s1) { rec.s1 = it.s1; rec.s2 = it.s2; }
    if (it.figure) rec.figure = it.figure;
    rec.opts = (it.format === 'qc' || it.format === 'ds') ? null : o.opts; // fixed sets live in choices
    rec.correct = o.correct;
    rec.move = it.move; rec.why = it.why;
    if (Object.keys(diag).length) rec.diag = diag;
    return rec;
  });
  const data = {
    version: new Date().toISOString().slice(0, 10),
    note: 'Generated by scripts/qr-formats/build.js. Do not edit by hand; edit scripts/qr-formats/src/*.js and rebuild.',
    formats: Object.fromEntries(Object.keys(SKILL).map((f) => [f, { skill: SKILL[f], label: LABEL[f], count: out.filter((x) => x.format === f).length }])),
    choices: { qc: require('./lib/check.js').QC_CHOICES, ds: require('./lib/check.js').DS_CHOICES },
    items: out
  };
  const json = JSON.stringify(data);
  fs.writeFileSync(path.join(ROOT, 'shared', 'qr-formats-bank.json'), JSON.stringify(data, null, 1) + '\n');
  fs.writeFileSync(path.join(ROOT, 'shared', 'qr-formats-bank.js'),
    '/* QR formats pool data. GENERATED by scripts/qr-formats/build.js; edit the sources, not this file.\n' +
    '   Runtime helpers: shared/qr-formats.js. Docs: docs/QR-FORMATS-POOL.md */\n' +
    '(function (d) { if (typeof module === "object" && module.exports) module.exports = d; if (typeof window !== "undefined") window.QR_FORMATS_DATA = d; })(' + json + ');\n');
  console.log('Wrote shared/qr-formats-bank.js and shared/qr-formats-bank.json');
}
main();
