#!/usr/bin/env node
// Builds tools/rc/data/bank.js from tools/rc/data/passages/*.json + sections.json.
// Refuses to write anything if the validator finds an error, so the player can only
// ever load a bank where every key has a proof line and no key is the longest choice.
//
//   node scripts/build-rc-bank.mjs

import fs from 'node:fs';
import path from 'node:path';
import { validateAll, TYPES, DATA } from './validate-rc.mjs';

const { errors, warns, byId, sections, stats } = validateAll();
for (const w of warns) console.log('  warn  ' + w);
if (errors.length) {
  for (const e of errors) console.log('  ERROR ' + e);
  console.log(`bank.js NOT written: ${errors.length} error(s)`);
  process.exit(1);
}

const keep = ['id', 'title', 'topic', 'field', 'source', 'words', 'paragraphs'];
const passages = {};
for (const [id, p] of Object.entries(byId)) {
  const out = {};
  for (const k of keep) out[k] = p[k];
  out.questions = p.questions.map((q) => ({
    id: q.id, type: q.type, stem: q.stem, choices: q.choices, key: q.key,
    proof: q.proof, why: q.why, distractorNotes: q.distractorNotes,
  }));
  passages[id] = out;
}

const bank = {
  version: new Date().toISOString().slice(0, 10),
  types: TYPES,
  passages,
  order: Object.keys(passages).sort((a, b) => {
    const oa = passages[a].source === 'original' ? 0 : 1;
    const ob = passages[b].source === 'original' ? 0 : 1;
    return oa - ob || a.localeCompare(b);
  }),
  sections,
};

const js = '/* GENERATED by scripts/build-rc-bank.mjs from tools/rc/data. Do not edit by hand. */\n'
  + 'window.ACE_RC_BANK = ' + JSON.stringify(bank) + ';\n';
fs.writeFileSync(path.join(DATA, 'bank.js'), js);
const q = stats.reduce((a, s) => a + s.questions, 0);
console.log(`bank.js written: ${stats.length} passages, ${q} questions, ${sections.length} sections, ${(js.length / 1024).toFixed(0)} KB`);
