'use strict';
/* Data interpretation items. Every item carries a `figure` (rendered by
   shared/qr-figures.js) and its key is recomputed from the figure data itself
   with cell()/val()/slice() lookups (scripts/qr-formats/lib/check.js). */
module.exports = [
  {
    id: 'di-001', format: 'di', topic: 'percent', diff: 2,
    figure: { type: 'table', title: 'Students enrolled in a summer science program', columns: ['Year', 'Biology', 'Chemistry', 'Physics'],
      rows: [['2021', 120, 80, 50], ['2022', 150, 90, 60], ['2023', 165, 72, 63]] },
    stem: 'According to the table, by what percent did total enrollment in the program increase from 2021 to 2023?',
    opts: ['8%', '12.5%', '16.7%', '18%', '20%'],
    answer: '20%',
    move: 'Percent change = (new - old) / old. The old value is always the denominator.',
    why: 'Add each row first. 2021: 120 + 80 + 50 = 250. 2023: 165 + 72 + 63 = 300. Change = 300 - 250 = 50. Percent change = 50 / 250 = 0.20 = 20%. The trap is dividing by the newer total: 50 / 300 is about 16.7%.',
    diag: {'16.7%': 'You divided the change by the 2023 total. Percent change always divides by the starting value.'},
    check: { num: '((cell("2023","Biology")+cell("2023","Chemistry")+cell("2023","Physics")) - (cell("2021","Biology")+cell("2021","Chemistry")+cell("2021","Physics"))) / (cell("2021","Biology")+cell("2021","Chemistry")+cell("2021","Physics")) * 100', round: 1 }
  },
  {
    id: 'di-002', format: 'di', topic: 'data', diff: 3,
    figure: { type: 'bar', title: 'Practice questions completed per month', categories: ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun'],
      series: [{ name: 'Questions', values: [20, 30, 36, 48, 45, 60] }], yLabel: 'Questions' },
    stem: 'Based on the chart, which month showed the greatest percent increase in questions completed over the previous month?',
    opts: ['Feb', 'Mar', 'Apr', 'May', 'Jun'],
    answer: 'Feb',
    move: 'Biggest jump in raw count is not the biggest percent jump: divide each change by its own starting value.',
    why: 'Compute each change over the month before it. February: (30 - 20) / 20 = 50%. March: (36 - 30) / 30 = 20%. April: (48 - 36) / 36 = 33.3%. May: (45 - 48) / 48 is a decrease. June: (60 - 45) / 45 = 33.3%. February wins at 50%, even though June has the largest raw increase (15). A small starting value makes a small jump a big percent.',
    diag: { Jun: 'June has the largest raw increase (15), but from a base of 45 that is only 33.3%.', Apr: 'April is 12 / 36 = 33.3%, well below February.' },
    check: { pickMax: { Feb: '(val("","Feb")-val("","Jan"))/val("","Jan")', Mar: '(val("","Mar")-val("","Feb"))/val("","Feb")', Apr: '(val("","Apr")-val("","Mar"))/val("","Mar")', May: '(val("","May")-val("","Apr"))/val("","Apr")', Jun: '(val("","Jun")-val("","May"))/val("","May")' } }
  },
  {
    id: 'di-003', format: 'di', topic: 'percent', diff: 2,
    figure: { type: 'pie', title: 'Preferred study method of 400 surveyed students', show: 'value',
      slices: [{ label: 'Flashcards', value: 120 }, { label: 'Practice tests', value: 100 }, { label: 'Videos', value: 80 }, { label: 'Textbook', value: 60 }, { label: 'Group study', value: 40 }] },
    stem: 'According to the chart, what percent of the surveyed students chose neither flashcards nor practice tests?',
    opts: ['25%', '30%', '35%', '40%', '45%'],
    answer: '45%',
    move: '"Neither" means add up everything else, or take the total minus the named groups.',
    why: 'Students who chose neither: 400 - 120 - 100 = 180 (the same as 80 + 60 + 40). As a percent of everyone surveyed: 180 / 400 = 0.45 = 45%. The 55% choice is the share that did pick flashcards or practice tests, the complement of what was asked.',
    diag: {'30%': 'Videos and group study alone give 30%. Textbook readers also chose neither flashcards nor practice tests.'},
    check: { num: '(pietotal() - slice("Flashcards") - slice("Practice tests")) / pietotal() * 100' }
  },
  {
    id: 'di-004', format: 'di', topic: 'statistics', diff: 1,
    figure: { type: 'table', title: 'Drinks sold at a campus cafe', columns: ['Day', 'Coffee', 'Tea', 'Smoothie'],
      rows: [['Mon', 120, 45, 30], ['Tue', 110, 50, 35], ['Wed', 130, 40, 25], ['Thu', 125, 55, 40], ['Fri', 150, 60, 45]] },
    stem: 'According to the table, what was the mean number of teas sold per day from Monday through Friday?',
    opts: ['50', '52.5', '55', '60', '62.5'],
    answer: '50',
    move: 'Mean = column total / number of rows; add down one column only.',
    why: 'Add the Tea column: 45 + 50 + 40 + 55 + 60 = 250. Divide by the 5 days: 250 / 5 = 50 teas per day. 62.5 comes from dividing by 4, as if one day were missing.',
    diag: {'62.5': 'There are five days in the table, so divide 250 by 5, not 4.', '60': 'That is Friday alone, not the mean of the week.'},
    check: { num: 'col("Tea")/5' }
  },
  {
    id: 'di-005', format: 'di', topic: 'ratios', diff: 3,
    figure: { type: 'table', title: 'Drinks sold at a campus cafe', columns: ['Day', 'Coffee', 'Tea', 'Smoothie'],
      rows: [['Mon', 120, 45, 30], ['Tue', 110, 50, 35], ['Wed', 130, 40, 25], ['Thu', 125, 55, 40], ['Fri', 150, 60, 45]] },
    stem: 'On which day did coffee make up the greatest fraction of all drinks sold that day?',
    opts: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri'],
    answer: 'Wed',
    move: 'A share of a total needs the total for each row; the biggest count is not always the biggest share.',
    why: 'Find each day\'s total and the coffee share. Mon: 120 / 195, about 0.615. Tue: 110 / 195, about 0.564. Wed: 130 / 195, about 0.667. Thu: 125 / 220, about 0.568. Fri: 150 / 255, about 0.588. Wednesday has the largest share, even though Friday sold the most coffee.',
    diag: { Fri: 'Friday sold the most coffee, but it also sold the most of everything else, so coffee is only about 59% of Friday.' },
    check: { pickMax: { Mon: 'cell("Mon","Coffee")/(cell("Mon","Coffee")+cell("Mon","Tea")+cell("Mon","Smoothie"))', Tue: 'cell("Tue","Coffee")/(cell("Tue","Coffee")+cell("Tue","Tea")+cell("Tue","Smoothie"))', Wed: 'cell("Wed","Coffee")/(cell("Wed","Coffee")+cell("Wed","Tea")+cell("Wed","Smoothie"))', Thu: 'cell("Thu","Coffee")/(cell("Thu","Coffee")+cell("Thu","Tea")+cell("Thu","Smoothie"))', Fri: 'cell("Fri","Coffee")/(cell("Fri","Coffee")+cell("Fri","Tea")+cell("Fri","Smoothie"))' } }
  },
  {
    id: 'di-006', format: 'di', topic: 'ratios', diff: 2,
    figure: { type: 'table', title: 'Seed germination trial', columns: ['Treatment', 'Planted', 'Germinated'],
      rows: [['Control', 80, 52], ['Water', 70, 49], ['Light', 60, 45], ['Heat', 50, 41], ['Shade', 40, 22]] },
    stem: 'Based on the table, which treatment had the lowest germination rate (seeds germinated divided by seeds planted)?',
    opts: ['Control', 'Water', 'Light', 'Heat', 'Shade'],
    answer: 'Shade',
    move: 'Compare rates, not counts: divide each row before you rank.',
    why: 'Rates: Control 52 / 80 = 0.65. Water 49 / 70 = 0.70. Light 45 / 60 = 0.75. Heat 41 / 50 = 0.82. Shade 22 / 40 = 0.55. Shade is lowest. Shade also has the fewest seeds germinated, but that alone would not prove it; Control loses the most seeds (28) yet has a higher rate.',
    diag: { Control: 'Control has the most seeds that failed (28), but it also planted the most. Its rate, 0.65, beats Shade at 0.55.' },
    check: { pickMin: { Control: 'cell("Control","Germinated")/cell("Control","Planted")', Water: 'cell("Water","Germinated")/cell("Water","Planted")', Light: 'cell("Light","Germinated")/cell("Light","Planted")', Heat: 'cell("Heat","Germinated")/cell("Heat","Planted")', Shade: 'cell("Shade","Germinated")/cell("Shade","Planted")' } }
  },
  {
    id: 'di-007', format: 'di', topic: 'percent', diff: 3,
    figure: { type: 'table', title: 'Seed germination trial', columns: ['Treatment', 'Planted', 'Germinated'],
      rows: [['Control', 80, 52], ['Water', 70, 49], ['Light', 60, 45], ['Heat', 50, 41], ['Shade', 40, 22]] },
    stem: 'Across all five treatments combined, what percent of the planted seeds germinated, to the nearest tenth of a percent?',
    opts: ['67.3%', '69.4%', '69.7%', '71.0%', '73.5%'],
    answer: '69.7%',
    move: 'An overall rate is total part over total whole; never average the row rates when the rows have different sizes.',
    why: 'Total planted: 80 + 70 + 60 + 50 + 40 = 300. Total germinated: 52 + 49 + 45 + 41 + 22 = 209. Overall rate: 209 / 300 = 0.6967, or 69.7%. Averaging the five row rates (0.65, 0.70, 0.75, 0.82, 0.55) gives 69.4%, which weights the small Shade group the same as the large Control group.',
    diag: { '69.4%': 'That is the average of the five rates. The groups have different sizes, so pool the counts first.' },
    check: { num: 'col("Germinated")/col("Planted")*100', round: 1 }
  },
  {
    id: 'di-008', format: 'di', topic: 'ratios', diff: 3,
    figure: { type: 'table', title: 'Monthly rainfall in two cities (mm)', columns: ['Month', 'City A', 'City B'],
      rows: [['Apr', 82, 64], ['May', 95, 71], ['Jun', 60, 88], ['Jul', 45, 102], ['Aug', 38, 96]] },
    stem: 'In how many of the months shown did City B receive more than 1.2 times the rainfall of City A?',
    opts: ['0', '1', '2', '3', '4'],
    answer: '3',
    move: 'Turn "more than 1.2 times" into a threshold for each row: compute 1.2 × A, then compare.',
    why: 'Compute 1.2 × City A for each month and compare with City B. Apr: 98.4 vs 64, no. May: 114 vs 71, no. Jun: 72 vs 88, yes. Jul: 54 vs 102, yes. Aug: 45.6 vs 96, yes. Three months.',
    diag: { '2': 'Check June: 1.2 × 60 = 72, and City B had 88, which is more.' },
    check: { num: 'iff(cell("Apr","City B") > 1.2*cell("Apr","City A"),1,0) + iff(cell("May","City B") > 1.2*cell("May","City A"),1,0) + iff(cell("Jun","City B") > 1.2*cell("Jun","City A"),1,0) + iff(cell("Jul","City B") > 1.2*cell("Jul","City A"),1,0) + iff(cell("Aug","City B") > 1.2*cell("Aug","City A"),1,0)' }
  },
  {
    id: 'di-009', format: 'di', topic: 'statistics', diff: 2,
    figure: { type: 'table', title: 'Monthly rainfall in two cities (mm)', columns: ['Month', 'City A', 'City B'],
      rows: [['Apr', 82, 64], ['May', 95, 71], ['Jun', 60, 88], ['Jul', 45, 102], ['Aug', 38, 96]] },
    stem: 'What was the difference between the mean monthly rainfall of City B and the mean monthly rainfall of City A over these five months, in millimeters?',
    opts: ['12', '16.4', '20.2', '24', '57'],
    answer: '20.2',
    move: 'Difference of means = (difference of totals) / count; one subtraction instead of two averages.',
    why: 'City A total: 82 + 95 + 60 + 45 + 38 = 320, mean 64. City B total: 64 + 71 + 88 + 102 + 96 = 421, mean 84.2. Difference: 84.2 - 64 = 20.2 mm. Shortcut: (421 - 320) / 5 = 101 / 5 = 20.2.',
    diag: { '24': 'That is the difference of the medians (88 - 64). The question asks about means.' },
    check: { num: 'col("City B")/5 - col("City A")/5' }
  },
  {
    id: 'di-010', format: 'di', topic: 'percent', diff: 2,
    figure: { type: 'table', title: 'Average weekday bus riders (thousands)', columns: ['Route', '2024', '2025'],
      rows: [['Route 1', 40, 46], ['Route 2', 25, 24], ['Route 3', 32, 40], ['Route 4', 18, 27], ['Route 5', 50, 60]] },
    stem: 'Which route had the greatest percent increase in riders from 2024 to 2025?',
    opts: ['Route 1', 'Route 2', 'Route 3', 'Route 4', 'Route 5'],
    answer: 'Route 4',
    move: 'Percent change rewards a small starting value; divide each change by its own 2024 number.',
    why: 'Route 1: 6 / 40 = 15%. Route 2: -1 / 25 = -4%. Route 3: 8 / 32 = 25%. Route 4: 9 / 18 = 50%. Route 5: 10 / 50 = 20%. Route 4 leads. Route 5 has the largest raw gain (10 thousand), but from the largest base.',
    diag: { 'Route 5': 'Route 5 gained the most riders, but 10 on a base of 50 is only 20%.' },
    check: { pickMax: { 'Route 1': '(cell("Route 1","2025")-cell("Route 1","2024"))/cell("Route 1","2024")', 'Route 2': '(cell("Route 2","2025")-cell("Route 2","2024"))/cell("Route 2","2024")', 'Route 3': '(cell("Route 3","2025")-cell("Route 3","2024"))/cell("Route 3","2024")', 'Route 4': '(cell("Route 4","2025")-cell("Route 4","2024"))/cell("Route 4","2024")', 'Route 5': '(cell("Route 5","2025")-cell("Route 5","2024"))/cell("Route 5","2024")' } }
  },
  {
    id: 'di-011', format: 'di', topic: 'percent', diff: 3,
    figure: { type: 'table', title: 'Average weekday bus riders (thousands)', columns: ['Route', '2024', '2025'],
      rows: [['Route 1', 40, 46], ['Route 2', 25, 24], ['Route 3', 32, 40], ['Route 4', 18, 27], ['Route 5', 50, 60]] },
    stem: 'By what percent did total weekday ridership on the five routes increase from 2024 to 2025, to the nearest tenth of a percent?',
    opts: ['14.0%', '16.2%', '19.4%', '21.2%', '32.0%'],
    answer: '19.4%',
    move: 'For a total, add the columns first, then take one percent change.',
    why: 'Total 2024: 40 + 25 + 32 + 18 + 50 = 165. Total 2025: 46 + 24 + 40 + 27 + 60 = 197. Change: 32. Percent: 32 / 165 = 0.1939, or 19.4%. Averaging the five route percents gives 21.2%, which is wrong because the routes have different sizes. Dividing by the 2025 total gives 16.2%.',
    diag: { '21.2%': 'That averages the route percents. Pool the riders, then divide once.', '16.2%': 'Divide the change by the starting total, 165, not by 197.' },
    check: { num: '(col("2025") - col("2024"))/col("2024")*100', round: 1 }
  },
  {
    id: 'di-012', format: 'di', topic: 'data', diff: 2,
    figure: { type: 'table', title: 'Print shop price per item (dollars)', columns: ['Item', '1 to 49', '50 or more'],
      rows: [['Poster', 6, 4.5], ['Flyer', 0.5, 0.35], ['Banner', 20, 16]], note: 'The price per item depends on how many of that item are ordered.' },
    stem: 'A customer orders 60 flyers and 3 posters. Using the price table, what is the total cost of the order?',
    opts: ['34.5 dollars', '39 dollars', '43.5 dollars', '48 dollars', '51 dollars'],
    answer: '39 dollars',
    move: 'Pick the tier row by row: each item\'s own quantity decides its price.',
    why: 'Flyers: 60 is in the 50 or more tier, so 60 × 0.35 = 21 dollars. Posters: 3 is in the 1 to 49 tier, so 3 × 6 = 18 dollars. Total: 21 + 18 = 39 dollars. Using the bulk price for the posters too gives 34.5; using the small-order price for the flyers gives 48.',
    diag: { '34.5 dollars': 'Only 3 posters were ordered, so they stay at the 1 to 49 price of 6 dollars.', '48 dollars': '60 flyers qualify for the 50 or more price, 0.35 each.' },
    check: { num: '60*cell("Flyer","50 or more") + 3*cell("Poster","1 to 49")' }
  },
  {
    id: 'di-013', format: 'di', topic: 'percent', diff: 2,
    figure: { type: 'table', title: 'Weekly study hours of 200 surveyed students', columns: ['Hours per week', 'Students'],
      rows: [['0 to 4', 30], ['5 to 9', 70], ['10 to 14', 60], ['15 to 19', 30], ['20 or more', 10]] },
    stem: 'According to the table, what percent of the surveyed students study fewer than 15 hours per week?',
    opts: ['45%', '50%', '65%', '80%', '85%'],
    answer: '80%',
    move: '"Fewer than" a boundary: add every row that sits completely below it.',
    why: 'Fewer than 15 hours covers the rows 0 to 4, 5 to 9, and 10 to 14: 30 + 70 + 60 = 160 students. As a percent of 200: 160 / 200 = 80%. Stopping one row early (30 + 70 = 100) gives 50%.',
    diag: { '50%': 'The 10 to 14 row is also below 15 hours. Include its 60 students.', '85%': 'The 15 to 19 row is not fewer than 15 hours.' },
    check: { num: '(cell("0 to 4","Students")+cell("5 to 9","Students")+cell("10 to 14","Students"))/col("Students")*100' }
  },
  {
    id: 'di-014', format: 'di', topic: 'statistics', diff: 2,
    figure: { type: 'table', title: 'Exercise minutes per week', columns: ['Participant', 'Week 1', 'Week 2'],
      rows: [['P1', 150, 180], ['P2', 90, 120], ['P3', 200, 170], ['P4', 60, 100], ['P5', 120, 150], ['P6', 180, 210]] },
    stem: 'What is the median of the six participants\' Week 2 exercise minutes?',
    opts: ['150', '155', '160', '170', '180'],
    answer: '160',
    move: 'Median of an even count: sort, then average the two middle values.',
    why: 'Sort the Week 2 values: 100, 120, 150, 170, 180, 210. With six values, the median is the mean of the 3rd and 4th: (150 + 170) / 2 = 160. The mean, 930 / 6 = 155, is a different measure.',
    diag: { '155': 'That is the mean of Week 2. The median uses only the middle two sorted values.', '170': 'Sort before picking the middle; 170 is the 4th value, and the median averages the 3rd and 4th.' },
    check: { num: 'median(cell("P1","Week 2"),cell("P2","Week 2"),cell("P3","Week 2"),cell("P4","Week 2"),cell("P5","Week 2"),cell("P6","Week 2"))' }
  },
  {
    id: 'di-015', format: 'di', topic: 'percent', diff: 3,
    figure: { type: 'table', title: 'Exercise minutes per week', columns: ['Participant', 'Week 1', 'Week 2'],
      rows: [['P1', 150, 180], ['P2', 90, 120], ['P3', 200, 170], ['P4', 60, 100], ['P5', 120, 150], ['P6', 180, 210]] },
    stem: 'For how many participants did weekly exercise minutes increase by more than 20% from Week 1 to Week 2?',
    opts: ['2', '3', '4', '5', '6'],
    answer: '3',
    move: '"More than 20%" means Week 2 must beat 1.2 × Week 1; exactly 20% does not count.',
    why: 'Compare Week 2 with 1.2 × Week 1. P1: 1.2 × 150 = 180, and Week 2 is exactly 180, so not more than 20%. P2: 108 vs 120, yes. P3: decreased. P4: 72 vs 100, yes. P5: 144 vs 150, yes. P6: 216 vs 210, no. Three participants.',
    diag: { '4': 'P1 rose exactly 20% (150 to 180). The question asks for more than 20%.' },
    check: { num: 'iff(cell("P1","Week 2") > 1.2*cell("P1","Week 1"),1,0)+iff(cell("P2","Week 2") > 1.2*cell("P2","Week 1"),1,0)+iff(cell("P3","Week 2") > 1.2*cell("P3","Week 1"),1,0)+iff(cell("P4","Week 2") > 1.2*cell("P4","Week 1"),1,0)+iff(cell("P5","Week 2") > 1.2*cell("P5","Week 1"),1,0)+iff(cell("P6","Week 2") > 1.2*cell("P6","Week 1"),1,0)' }
  },
  {
    id: 'di-016', format: 'di', topic: 'data', diff: 2,
    figure: { type: 'table', title: 'Drug concentration in blood after one dose', columns: ['Hour', 'Concentration (mg/L)'],
      rows: [['0', 80], ['2', 40], ['4', 20], ['6', 10], ['8', 5]] },
    stem: 'If the pattern in the table continues, what will the concentration be at hour 12, in mg/L?',
    opts: ['0', '1.25', '2.5', '3.75', '5'],
    answer: '1.25',
    move: 'Spot the rule first: equal time steps with equal ratios means repeated halving, not a straight line.',
    why: 'Each 2 hours the concentration halves: 80, 40, 20, 10, 5. Continue: hour 10 is 2.5, hour 12 is 1.25. A straight-line guess (dropping 5 every 2 hours from hour 6 to 8) would reach 0 too early; halving never reaches 0.',
    diag: { '2.5': 'That is hour 10. One more 2-hour step halves it again.', '0': 'Halving shrinks the amount but never drops it to zero.' },
    check: { num: 'cell("8","Concentration (mg/L)")*(cell("2","Concentration (mg/L)")/cell("0","Concentration (mg/L)"))^2' }
  },
  {
    id: 'di-017', format: 'di', topic: 'percent', diff: 2,
    figure: { type: 'bar', title: 'Volunteers by age group', categories: ['18-24', '25-34', '35-44', '45-54', '55+'],
      series: [{ name: '2024', values: [40, 55, 35, 30, 20] }, { name: '2025', values: [50, 50, 42, 36, 32] }], yLabel: 'Volunteers' },
    stem: 'Which age group had the greatest percent increase in volunteers from 2024 to 2025?',
    opts: ['18-24', '25-34', '35-44', '45-54', '55+'],
    answer: '55+',
    move: 'Percent change: (2025 - 2024) / 2024 for each pair of bars.',
    why: '18-24: 10 / 40 = 25%. 25-34: a decrease. 35-44: 7 / 35 = 20%. 45-54: 6 / 30 = 20%. 55+: 12 / 20 = 60%. The 55+ group rose the most in percent and in raw count.',
    diag: { '18-24': '18-24 rose by 10 on a base of 40, which is 25%. 55+ rose by 12 on a base of 20.' },
    check: { pickMax: { '18-24': '(val("2025","18-24")-val("2024","18-24"))/val("2024","18-24")', '25-34': '(val("2025","25-34")-val("2024","25-34"))/val("2024","25-34")', '35-44': '(val("2025","35-44")-val("2024","35-44"))/val("2024","35-44")', '45-54': '(val("2025","45-54")-val("2024","45-54"))/val("2024","45-54")', '55+': '(val("2025","55+")-val("2024","55+"))/val("2024","55+")' } }
  },
  {
    id: 'di-018', format: 'di', topic: 'percent', diff: 3,
    figure: { type: 'bar', title: 'Volunteers by age group', categories: ['18-24', '25-34', '35-44', '45-54', '55+'],
      series: [{ name: '2024', values: [40, 55, 35, 30, 20] }, { name: '2025', values: [50, 50, 42, 36, 32] }], yLabel: 'Volunteers' },
    stem: 'By what percent did the total number of volunteers increase from 2024 to 2025, to the nearest tenth of a percent?',
    opts: ['10.0%', '14.3%', '16.7%', '20.0%', '30.0%'],
    answer: '16.7%',
    move: 'Total percent change: sum each year, then (new - old) / old.',
    why: '2024 total: 40 + 55 + 35 + 30 + 20 = 180. 2025 total: 50 + 50 + 42 + 36 + 32 = 210. Increase: 30. Percent: 30 / 180 = 0.1667, or 16.7%. Dividing by 210 instead gives 14.3%.',
    diag: { '14.3%': 'Use the 2024 total (180) as the base, not 210.' },
    check: { num: '(seriessum("2025")-seriessum("2024"))/seriessum("2024")*100', round: 1 }
  },
  {
    id: 'di-019', format: 'di', topic: 'statistics', diff: 2,
    figure: { type: 'bar', title: 'Household electricity use by month', categories: ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun'],
      series: [{ name: 'kWh', values: [640, 580, 500, 430, 410, 560] }], yLabel: 'kWh' },
    stem: 'What was the household\'s mean monthly electricity use for the six months shown?',
    opts: ['520 kWh', '525 kWh', '530 kWh', '560 kWh', '624 kWh'],
    answer: '520 kWh',
    move: 'Mean of a bar chart: add every bar, divide by the number of bars.',
    why: 'Sum: 640 + 580 + 500 + 430 + 410 + 560 = 3,120. Six months: 3,120 / 6 = 520 kWh. The median would be (500 + 560) / 2 = 530, and dividing by 5 gives 624.',
    diag: { '530 kWh': 'That is the median of the six values, not the mean.', '624 kWh': 'There are six bars, so divide by 6.' },
    check: { num: 'seriessum("kWh")/6' }
  },
  {
    id: 'di-020', format: 'di', topic: 'percent', diff: 3,
    figure: { type: 'bar', title: 'Average commute time by town', categories: ['Ashford', 'Belmont', 'Carver', 'Dalton', 'Easton', 'Fulton'],
      series: [{ name: 'Minutes', values: [24, 31, 18, 27, 35, 22] }], yLabel: 'Minutes', orientation: 'horizontal' },
    stem: 'The longest average commute shown is what percent longer than the shortest, to the nearest tenth of a percent?',
    opts: ['48.6%', '51.4%', '94.4%', '105.6%', '194.4%'],
    answer: '94.4%',
    move: '"Percent longer than X" divides the difference by X, the thing being compared against.',
    why: 'Longest: Easton, 35 minutes. Shortest: Carver, 18 minutes. Difference: 17. Percent longer than the shortest: 17 / 18 = 0.944, or 94.4%. Dividing by 35 gives 48.6% (wrong base), and 35 / 18 = 194.4% is the ratio, not the increase.',
    diag: { '48.6%': 'The base is the shortest commute (18), because the question compares to it.', '194.4%': '35 / 18 says Easton is 194.4% of Carver; subtract 100% to get how much longer.' },
    check: { num: '(val("","Easton")-val("","Carver"))/val("","Carver")*100', round: 1 }
  },
  {
    id: 'di-021', format: 'di', topic: 'data', diff: 2,
    figure: { type: 'bar', title: 'Scores before and after a review course', categories: ['Algebra', 'Stats', 'Percent', 'Ratios', 'Probability'],
      series: [{ name: 'Before', values: [62, 55, 58, 70, 48] }, { name: 'After', values: [74, 68, 70, 76, 66] }], yLabel: 'Score' },
    stem: 'In which topic was the improvement from before to after the smallest, in points?',
    opts: ['Algebra', 'Stats', 'Percent', 'Ratios', 'Probability'],
    answer: 'Ratios',
    move: 'Read each pair of bars as a gap; the smallest gap wins, not the shortest bar.',
    why: 'Improvements: Algebra 74 - 62 = 12. Stats 68 - 55 = 13. Percent 70 - 58 = 12. Ratios 76 - 70 = 6. Probability 66 - 48 = 18. Ratios improved least. Probability has the lowest scores but the biggest gain.',
    diag: { Probability: 'Probability has the shortest bars, but its gain (18 points) is the largest.' },
    check: { pickMin: { Algebra: 'val("After","Algebra")-val("Before","Algebra")', Stats: 'val("After","Stats")-val("Before","Stats")', Percent: 'val("After","Percent")-val("Before","Percent")', Ratios: 'val("After","Ratios")-val("Before","Ratios")', Probability: 'val("After","Probability")-val("Before","Probability")' } }
  },
  {
    id: 'di-022', format: 'di', topic: 'statistics', diff: 2,
    figure: { type: 'bar', title: 'Scores before and after a review course', categories: ['Algebra', 'Stats', 'Percent', 'Ratios', 'Probability'],
      series: [{ name: 'Before', values: [62, 55, 58, 70, 48] }, { name: 'After', values: [74, 68, 70, 76, 66] }], yLabel: 'Score' },
    stem: 'What was the mean improvement, in points, across the five topics?',
    opts: ['6', '11.2', '12', '12.2', '13'],
    answer: '12.2',
    move: 'Mean change = (sum of after - sum of before) / count.',
    why: 'Sum after: 74 + 68 + 70 + 76 + 66 = 354. Sum before: 62 + 55 + 58 + 70 + 48 = 293. Difference: 61. Mean improvement: 61 / 5 = 12.2 points. The median improvement is 12, a different measure.',
    diag: { '12': 'That is the median of the improvements (6, 12, 12, 13, 18). The mean is 61 / 5.' },
    check: { num: '(seriessum("After") - seriessum("Before"))/5' }
  },
  {
    id: 'di-023', format: 'di', topic: 'percent', diff: 1,
    figure: { type: 'bar', title: 'Science museum visitors (hundreds)', categories: ['Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'],
      series: [{ name: 'Visitors', values: [12, 9, 11, 15, 28, 25] }], yLabel: 'Hundreds of visitors' },
    stem: 'What percent of the week\'s visitors came on Saturday or Sunday?',
    opts: ['43%', '47%', '50%', '53%', '56%'],
    answer: '53%',
    move: 'Part over whole: add the bars you want, then divide by all the bars.',
    why: 'Weekend: 28 + 25 = 53 hundred. Whole week: 12 + 9 + 11 + 15 + 28 + 25 = 100 hundred. 53 / 100 = 53%.',
    diag: { '47%': 'That is the weekday share, the complement of what was asked.' },
    check: { num: '(val("","Sat")+val("","Sun"))/seriessum("Visitors")*100' }
  },
  {
    id: 'di-024', format: 'di', topic: 'percent', diff: 2,
    figure: { type: 'bar', title: 'Library books borrowed by genre', categories: ['Fiction', 'Mystery', 'Science', 'History', 'Poetry'],
      series: [{ name: 'Books', values: [420, 260, 180, 140, 50] }], yLabel: 'Books' },
    stem: 'The number of science books borrowed was what percent of the number of fiction books borrowed, to the nearest tenth of a percent?',
    opts: ['17.1%', '35.7%', '42.9%', '57.1%', '233.3%'],
    answer: '42.9%',
    move: '"A is what percent of B" means A / B, with B after the word "of."',
    why: 'Science / Fiction = 180 / 420 = 0.4286, or 42.9%. The reverse, 420 / 180, is 233.3%. Science out of all books (1,050) is 17.1%. And 57.1% is how much smaller science is than fiction.',
    diag: { '233.3%': 'That is fiction as a percent of science. The base is the number after "of": fiction.', '17.1%': 'That compares science with all 1,050 books, not with fiction.' },
    check: { num: 'val("","Science")/val("","Fiction")*100', round: 1 }
  },
  {
    id: 'di-025', format: 'di', topic: 'percent', diff: 3,
    figure: { type: 'bar', title: 'Units sold by store and quarter', categories: ['Q1', 'Q2', 'Q3', 'Q4'],
      series: [{ name: 'North', values: [30, 45, 40, 55] }, { name: 'South', values: [35, 30, 50, 45] }, { name: 'West', values: [20, 35, 30, 40] }], yLabel: 'Units' },
    stem: 'For the full year, West\'s total units sold were what percent of North\'s total, to the nearest tenth of a percent?',
    opts: ['26.5%', '36.0%', '73.5%', '78.1%', '136.0%'],
    answer: '73.5%',
    move: 'Total each series across the quarters before comparing the stores.',
    why: 'North: 30 + 45 + 40 + 55 = 170. West: 20 + 35 + 30 + 40 = 125. West as a percent of North: 125 / 170 = 0.7353, or 73.5%. Comparing West to South (160) instead gives 78.1%.',
    diag: { '136.0%': 'That is North as a percent of West. The base here is North.', '78.1%': 'That compares West with South. The question compares West with North.' },
    check: { num: 'seriessum("West")/seriessum("North")*100', round: 1 }
  },
  {
    id: 'di-026', format: 'di', topic: 'data', diff: 2,
    figure: { type: 'bar', title: 'Monthly profit of a small business (thousands of dollars)', categories: ['Jan', 'Feb', 'Mar', 'Apr', 'May'],
      series: [{ name: 'Profit', values: [12, -4, 8, -6, 15] }], yLabel: 'Thousands of dollars' },
    stem: 'What was the business\'s total profit for the five months shown, in thousands of dollars?',
    opts: ['15', '25', '35', '45', '49'],
    answer: '25',
    move: 'Bars below the axis are negative: subtract them.',
    why: 'Add with signs: 12 + (-4) + 8 + (-6) + 15 = 25 thousand dollars. Adding the losses as if they were gains gives 12 + 4 + 8 + 6 + 15 = 45.',
    diag: { '45': 'February and April fall below zero; they are losses and must be subtracted.', '35': 'Only the positive months were counted. Include the two losses.' },
    check: { num: 'seriessum("Profit")' }
  },
  {
    id: 'di-027', format: 'di', topic: 'statistics', diff: 2,
    figure: { type: 'bar', title: 'Steps walked per day (thousands)', categories: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'],
      series: [{ name: 'Steps', values: [6, 8, 5, 10, 7, 12, 9] }], yLabel: 'Thousands of steps' },
    stem: 'On how many of the days shown was the step count above the mean for the week?',
    opts: ['2', '3', '4', '5', '6'],
    answer: '3',
    move: 'Find the mean first, then count bars strictly above it.',
    why: 'Mean: (6 + 8 + 5 + 10 + 7 + 12 + 9) / 7 = 57 / 7, about 8.14 thousand. Days above 8.14: Thursday (10), Saturday (12), and Sunday (9). Tuesday at 8 is just under. Three days.',
    diag: { '4': 'Tuesday (8 thousand) is just below the mean of about 8.14.' },
    check: { num: 'iff(val("","Mon") > seriessum("Steps")/7,1,0)+iff(val("","Tue") > seriessum("Steps")/7,1,0)+iff(val("","Wed") > seriessum("Steps")/7,1,0)+iff(val("","Thu") > seriessum("Steps")/7,1,0)+iff(val("","Fri") > seriessum("Steps")/7,1,0)+iff(val("","Sat") > seriessum("Steps")/7,1,0)+iff(val("","Sun") > seriessum("Steps")/7,1,0)' }
  },
  {
    id: 'di-028', format: 'di', topic: 'percent', diff: 3,
    figure: { type: 'bar', title: 'Average nightly sleep by age group', categories: ['18-24', '25-34', '35-44', '45-54', '55-64'],
      series: [{ name: 'Weekday', values: [6.5, 7, 6.5, 6, 6.5] }, { name: 'Weekend', values: [9, 8.5, 7.5, 7, 7.5] }], yLabel: 'Hours' },
    stem: 'For which age group is the weekend average the greatest percent above the weekday average?',
    opts: ['18-24', '25-34', '35-44', '45-54', '55-64'],
    answer: '18-24',
    move: 'Same idea as percent change: (weekend - weekday) / weekday for each group.',
    why: '18-24: 2.5 / 6.5, about 38.5%. 25-34: 1.5 / 7, about 21.4%. 35-44: 1 / 6.5, about 15.4%. 45-54: 1 / 6, about 16.7%. 55-64: 1 / 6.5, about 15.4%. The 18-24 group has the biggest relative jump.',
    check: { pickMax: { '18-24': '(val("Weekend","18-24")-val("Weekday","18-24"))/val("Weekday","18-24")', '25-34': '(val("Weekend","25-34")-val("Weekday","25-34"))/val("Weekday","25-34")', '35-44': '(val("Weekend","35-44")-val("Weekday","35-44"))/val("Weekday","35-44")', '45-54': '(val("Weekend","45-54")-val("Weekday","45-54"))/val("Weekday","45-54")', '55-64': '(val("Weekend","55-64")-val("Weekday","55-64"))/val("Weekday","55-64")' } }
  },
  {
    id: 'di-029', format: 'di', topic: 'ratios', diff: 2,
    figure: { type: 'bar', title: 'Favorite study location of surveyed students', categories: ['Library', 'Home', 'Cafe', 'Dorm', 'Park'],
      series: [{ name: 'Students', values: [48, 72, 30, 54, 16] }], yLabel: 'Students', orientation: 'horizontal' },
    stem: 'If the same proportions hold for a group of 330 students, how many of them would choose the library?',
    opts: ['72', '80', '96', '108', '120'],
    answer: '72',
    move: 'Scale a share: (part / survey total) × new total.',
    why: 'Survey total: 48 + 72 + 30 + 54 + 16 = 220. Library share: 48 / 220. For 330 students: 48 / 220 × 330 = 48 × 1.5 = 72. Note 72 is also the Home bar, so read the question, not the chart, to know which group you want.',
    diag: {'108': 'That scales the Home count (72 × 1.5), not the Library count.'},
    check: { num: 'val("","Library")/seriessum("Students")*330' }
  },
  {
    id: 'di-030', format: 'di', topic: 'graphical', diff: 3,
    figure: { type: 'bar', title: 'Population of a town (thousands)', categories: ['2000', '2005', '2010', '2015', '2020'],
      series: [{ name: 'Population', values: [24, 27, 30, 33, 36] }], yLabel: 'Thousands' },
    stem: 'If the population continues to grow by the same amount every 5 years, in what year will it first reach 45 thousand?',
    opts: ['2030', '2035', '2040', '2045', '2050'],
    answer: '2035',
    move: 'Constant step: find the step per interval, then count steps to the target.',
    why: 'The population rises 3 thousand every 5 years. From 36 thousand in 2020 to 45 thousand is 9 thousand more, which is 3 steps of 5 years. 2020 + 15 = 2035. Check: 2025 is 39, 2030 is 42, 2035 is 45.',
    diag: { '2030': '2030 gives 42 thousand. One more 5-year step is needed to reach 45.' },
    check: { num: '2020 + (45 - val("","2020"))/((val("","2020") - val("","2000"))/20)' }
  },
  {
    id: 'di-031', format: 'di', topic: 'ratios', diff: 3,
    figure: { type: 'bar', title: 'Applications and acceptances by program', categories: ['Nursing', 'Biology', 'Chemistry', 'Physics', 'Math'],
      series: [{ name: 'Applied', values: [400, 300, 200, 100, 150] }, { name: 'Accepted', values: [120, 105, 80, 45, 60] }], yLabel: 'Students' },
    stem: 'Which program had the highest acceptance rate (accepted divided by applied)?',
    opts: ['Nursing', 'Biology', 'Chemistry', 'Physics', 'Math'],
    answer: 'Physics',
    move: 'Rate = part / whole for each program; the biggest bars do not decide it.',
    why: 'Nursing 120 / 400 = 30%. Biology 105 / 300 = 35%. Chemistry 80 / 200 = 40%. Physics 45 / 100 = 45%. Math 60 / 150 = 40%. Physics has the highest rate despite the fewest acceptances.',
    diag: { Nursing: 'Nursing accepted the most students, but out of 400 applicants that is only 30%.' },
    check: { pickMax: { Nursing: 'val("Accepted","Nursing")/val("Applied","Nursing")', Biology: 'val("Accepted","Biology")/val("Applied","Biology")', Chemistry: 'val("Accepted","Chemistry")/val("Applied","Chemistry")', Physics: 'val("Accepted","Physics")/val("Applied","Physics")', Math: 'val("Accepted","Math")/val("Applied","Math")' } }
  },
  {
    id: 'di-032', format: 'di', topic: 'percent', diff: 4,
    figure: { type: 'bar', title: 'Resale value of a bicycle by age', categories: ['1 yr', '2 yr', '3 yr', '4 yr', '5 yr'],
      series: [{ name: 'Dollars', values: [400, 340, 289, 245.65, 208.8] }], yLabel: 'Dollars' },
    stem: 'The value falls by the same percent each year. If that continues, what will the bicycle be worth at 7 years old, to the nearest dollar?',
    opts: ['151 dollars', '160 dollars', '177 dollars', '209 dollars', '245 dollars'],
    answer: '151 dollars',
    move: 'Constant percent drop: find the yearly multiplier, then raise it to the number of years.',
    why: 'From 400 to 340 is a drop of 60, or 15%, so each year multiplies the value by 0.85 (340 to 289 is also 15%). From age 1 to age 7 is 6 years: 400 × 0.85^6 = 400 × 0.37715 = 150.86, about 151 dollars. Subtracting 60 every year (a straight line) gives 40, and stopping at 6 years old gives 177.',
    diag: {'177 dollars': 'That is the value at 6 years old (five steps from age 1). Age 7 needs six steps.', '209 dollars': 'That is the value shown for age 5. Two more years of 15% drops remain.'},
    check: { num: 'val("","1 yr")*(val("","2 yr")/val("","1 yr"))^6', round: 0 }
  },
  {
    id: 'di-033', format: 'di', topic: 'rates', diff: 2,
    figure: { type: 'line', title: 'Temperature of a cooling cup of tea', x: ['0', '5', '10', '15', '20', '25'],
      series: [{ name: 'Degrees C', values: [90, 74, 62, 53, 46, 41] }], yLabel: 'Degrees C', xLabel: 'Minutes' },
    stem: 'What was the average rate of cooling, in degrees per minute, from minute 5 to minute 20, to the nearest hundredth?',
    opts: ['0.93', '1.47', '1.87', '1.96', '5.6'],
    answer: '1.87',
    move: 'Average rate = change in value / change in time, using only the two endpoints asked for.',
    why: 'At minute 5 the tea is 74 degrees; at minute 20 it is 46. Change: 28 degrees over 15 minutes. 28 / 15 = 1.867, about 1.87 degrees per minute. Using the whole graph (49 over 25) gives 1.96, which answers a different interval.',
    diag: { '1.96': 'That uses minutes 0 to 25. The question asks about minutes 5 to 20.', '5.6': 'Divide by the 15 minutes elapsed, not by the 5-minute spacing between points.' },
    check: { num: '(val("","5")-val("","20"))/(20-5)', round: 2 }
  },
  {
    id: 'di-034', format: 'di', topic: 'graphical', diff: 2,
    figure: { type: 'line', title: 'Monthly subscribers to two apps (thousands)', x: ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun'],
      series: [{ name: 'App A', values: [20, 25, 30, 35, 40, 45] }, { name: 'App B', values: [5, 10, 20, 30, 40, 50] }], yLabel: 'Thousands', valueLabels: false },
    stem: 'In which month did App B first have more subscribers than App A?',
    opts: ['Feb', 'Mar', 'Apr', 'May', 'Jun'],
    answer: 'Jun',
    move: 'Where two lines meet is a tie, not a lead; look for the first point strictly above.',
    why: 'Read both lines month by month. Through April, App A is ahead. In May both are at 40 thousand, a tie. In June App B reaches 50 thousand against 45 for App A, its first month in front.',
    diag: { May: 'In May the lines meet at 40 thousand. Equal is not more.' },
    check: { pickMin: { Feb: 'iff(val("App B","Feb") > val("App A","Feb"), 2, 99)', Mar: 'iff(val("App B","Mar") > val("App A","Mar"), 3, 99)', Apr: 'iff(val("App B","Apr") > val("App A","Apr"), 4, 99)', May: 'iff(val("App B","May") > val("App A","May"), 5, 99)', Jun: 'iff(val("App B","Jun") > val("App A","Jun"), 6, 99)' } }
  },
  {
    id: 'di-035', format: 'di', topic: 'rates', diff: 4,
    figure: { type: 'line', title: 'Monthly subscribers to two apps (thousands)', x: ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun'],
      series: [{ name: 'App A', values: [20, 25, 30, 35, 40, 45] }, { name: 'App B', values: [5, 10, 20, 30, 40, 50] }], yLabel: 'Thousands', valueLabels: false },
    stem: 'Define each app\'s growth factor as its June total divided by its January total. App B\'s growth factor is how many times App A\'s growth factor, to the nearest hundredth?',
    opts: ['2.25', '4.44', '6.25', '8', '10'],
    answer: '4.44',
    move: 'Growth factor = end / start for each line; then compare the two factors.',
    why: 'App B grew from 5 to 50, a factor of 10. App A grew from 20 to 45, a factor of 2.25. Compare: 10 / 2.25 = 4.444, so App B\'s growth factor is about 4.44 times App A\'s. The numbers 10 and 2.25 alone are each app\'s own factor.',
    diag: { '10': 'That is App B\'s own growth factor. The question compares it with App A\'s factor of 2.25.' },
    check: { num: '(val("App B","Jun")/val("App B","Jan"))/(val("App A","Jun")/val("App A","Jan"))', round: 2 }
  },
  {
    id: 'di-036', format: 'di', topic: 'rates', diff: 4,
    figure: { type: 'line', title: 'Product concentration during a reaction', x: ['0', '10', '20', '30', '40', '50'],
      series: [{ name: 'mM', values: [0, 18, 32, 42, 48, 50] }], yLabel: 'Concentration (mM)', xLabel: 'Minutes' },
    stem: 'The average rate of product formation during the first 20 minutes was how many times the average rate from minute 20 to minute 50, to the nearest hundredth?',
    opts: ['0.38', '1.6', '1.78', '2.67', '4'],
    answer: '2.67',
    move: 'Compare rates, not changes: divide each change by its own time window.',
    why: 'First 20 minutes: 32 mM / 20 min = 1.6 mM per minute. Minutes 20 to 50: (50 - 32) / 30 = 18 / 30 = 0.6 mM per minute. Ratio: 1.6 / 0.6 = 2.667, about 2.67. Comparing the raw changes (32 vs 18) gives 1.78, which ignores the different window lengths.',
    diag: { '1.78': 'The windows are 20 and 30 minutes long; divide each change by its own time first.' },
    check: { num: '((val("","20")-val("","0"))/20)/((val("","50")-val("","20"))/30)', round: 2 }
  },
  {
    id: 'di-037', format: 'di', topic: 'exponents', diff: 3,
    figure: { type: 'line', title: 'Bacteria in a culture (thousands)', x: ['0', '1', '2', '3', '4', '5'],
      series: [{ name: 'Thousands', values: [2, 4, 8, 16, 32, 64] }], yLabel: 'Thousands', xLabel: 'Hours' },
    stem: 'If the culture keeps growing in the same pattern, after how many whole hours will it first exceed 1,000 thousand bacteria?',
    opts: ['9', '10', '12', '15', '34'],
    answer: '9',
    move: 'Doubling: keep doubling from the last point and count the hours until you pass the target.',
    why: 'The count doubles every hour. Continue from 64 at hour 5: 128 at hour 6, 256 at 7, 512 at 8, 1,024 at 9. Hour 9 is the first to exceed 1,000. A straight-line guess using the last jump (32 per hour) would take about 29 more hours.',
    diag: {'10': 'Count the doublings from hour 5: 128, 256, 512, 1,024. Hour 9 already passes 1,000.'},
    check: { num: '5 + steps(val("","5"), val("","5")/val("","4"), 1000)' }
  },
  {
    id: 'di-038', format: 'di', topic: 'data', diff: 3,
    figure: { type: 'line', title: 'Average monthly temperature in three cities', x: ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun'],
      series: [{ name: 'City X', values: [30, 35, 45, 55, 65, 75] }, { name: 'City Y', values: [50, 50, 55, 60, 65, 70] }, { name: 'City Z', values: [10, 15, 30, 45, 60, 70] }], yLabel: 'Degrees F', yStep: 10, valueLabels: false },
    stem: 'In how many of the months shown was City Z\'s average temperature lower than that of both other cities?',
    opts: ['2', '3', '4', '5', '6'],
    answer: '5',
    move: '"Lower than both" means beat each other line separately in that month; ties fail.',
    why: 'Check City Z against X and Y each month. Jan 10 (vs 30, 50): yes. Feb 15 (35, 50): yes. Mar 30 (45, 55): yes. Apr 45 (55, 60): yes. May 60 (65, 65): yes. Jun 70 (75, 70): no, it ties City Y. Five months.',
    diag: { '6': 'In June City Z (70) equals City Y (70), so it is not lower than both.' },
    check: { num: 'iff(val("City Z","Jan") < min(val("City X","Jan"),val("City Y","Jan")),1,0)+iff(val("City Z","Feb") < min(val("City X","Feb"),val("City Y","Feb")),1,0)+iff(val("City Z","Mar") < min(val("City X","Mar"),val("City Y","Mar")),1,0)+iff(val("City Z","Apr") < min(val("City X","Apr"),val("City Y","Apr")),1,0)+iff(val("City Z","May") < min(val("City X","May"),val("City Y","May")),1,0)+iff(val("City Z","Jun") < min(val("City X","Jun"),val("City Y","Jun")),1,0)' }
  },
  {
    id: 'di-039', format: 'di', topic: 'percent', diff: 3,
    figure: { type: 'line', title: 'Concert ticket price by year', x: ['2018', '2019', '2020', '2021', '2022', '2023'],
      series: [{ name: 'Dollars', values: [20, 22, 22, 25, 29, 30] }], yLabel: 'Dollars' },
    stem: 'Between which two consecutive years did the ticket price increase by the greatest percent?',
    opts: ['2018-2019', '2019-2020', '2020-2021', '2021-2022', '2022-2023'],
    answer: '2021-2022',
    move: 'Steepest percent climb = biggest (change / starting value), checked pair by pair.',
    why: '2018-2019: 2 / 20 = 10%. 2019-2020: 0%. 2020-2021: 3 / 22, about 13.6%. 2021-2022: 4 / 25 = 16%. 2022-2023: 1 / 29, about 3.4%. The largest is 2021 to 2022.',
    diag: { '2020-2021': 'A 3 dollar rise on 22 is about 13.6%; the next year rose 4 dollars on 25, which is 16%.' },
    check: { pickMax: { '2018-2019': '(val("","2019")-val("","2018"))/val("","2018")', '2019-2020': '(val("","2020")-val("","2019"))/val("","2019")', '2020-2021': '(val("","2021")-val("","2020"))/val("","2020")', '2021-2022': '(val("","2022")-val("","2021"))/val("","2021")', '2022-2023': '(val("","2023")-val("","2022"))/val("","2022")' } }
  },
  {
    id: 'di-040', format: 'di', topic: 'graphical', diff: 2,
    figure: { type: 'line', title: 'Water level in a reservoir', x: ['1', '2', '3', '4', '5', '6', '7', '8'],
      series: [{ name: 'Meters', values: [12, 11.5, 11, 10.5, 10, 9.5, 9, 8.5] }], yLabel: 'Meters', xLabel: 'Week' },
    stem: 'If the level keeps falling at the same rate, in which week will it first fall below 6 meters?',
    opts: ['11', '12', '13', '14', '15'],
    answer: '14',
    move: '"Below" a level is the step after you reach it exactly.',
    why: 'The level drops 0.5 meters per week. From 8.5 meters in week 8, it takes (8.5 - 6) / 0.5 = 5 more weeks to reach exactly 6 meters, in week 13. It first falls below 6 one week later, in week 14 (5.5 meters).',
    diag: { '13': 'In week 13 the level is exactly 6 meters. Below 6 happens in week 14.' },
    check: { num: '8 + floor((val("","8") - 6)/(val("","7") - val("","8"))) + 1' }
  },
  {
    id: 'di-041', format: 'di', topic: 'percent', diff: 2,
    figure: { type: 'line', title: 'Weekly hours: studying vs gaming', x: ['Wk 1', 'Wk 2', 'Wk 3', 'Wk 4', 'Wk 5', 'Wk 6'],
      series: [{ name: 'Studying', values: [10, 12, 14, 16, 18, 20] }, { name: 'Gaming', values: [22, 19, 16, 13, 10, 7] }], yLabel: 'Hours', valueLabels: true },
    stem: 'In week 6, studying time was what percent of the total time spent on studying and gaming combined, to the nearest tenth of a percent?',
    opts: ['25.9%', '35.0%', '65.0%', '74.1%', '285.7%'],
    answer: '74.1%',
    move: 'Percent of a combined total: part / (part + other part).',
    why: 'Week 6: studying 20 hours, gaming 7 hours, total 27. Studying share: 20 / 27 = 0.7407, or 74.1%. Gaming is the other 25.9%. Comparing studying with gaming alone gives 20 / 7 = 285.7%, which answers a different question.',
    diag: { '285.7%': 'That is studying as a percent of gaming. The base is the combined total, 27 hours.' },
    check: { num: 'val("Studying","Wk 6")/(val("Studying","Wk 6")+val("Gaming","Wk 6"))*100', round: 1 }
  },
  {
    id: 'di-042', format: 'di', topic: 'data', diff: 3,
    figure: { type: 'line', title: 'Total miles run since the start of a training plan', x: ['Wk 1', 'Wk 2', 'Wk 3', 'Wk 4', 'Wk 5', 'Wk 6'],
      series: [{ name: 'Miles', values: [15, 32, 51, 72, 95, 120] }], yLabel: 'Total miles' },
    stem: 'The graph shows the running total of miles. How many miles did the runner run during week 4 alone?',
    opts: ['18', '21', '24', '51', '72'],
    answer: '21',
    move: 'A running total: one period is the difference between consecutive points.',
    why: 'The graph is cumulative, so each point is everything run so far. Week 4 alone is the total after week 4 minus the total after week 3: 72 - 51 = 21 miles. Reading 72 straight off the graph gives the total through week 4, not week 4 itself.',
    diag: { '72': 'That is the total through week 4. Subtract the 51 miles already run by the end of week 3.' },
    check: { num: 'val("","Wk 4") - val("","Wk 3")' }
  },
  {
    id: 'di-043', format: 'di', topic: 'statistics', diff: 2,
    figure: { type: 'line', title: 'Quarterly unemployment rate', x: ['Q1', 'Q2', 'Q3', 'Q4', 'Q5', 'Q6', 'Q7', 'Q8'],
      series: [{ name: 'Rate', values: [5.2, 5.0, 4.8, 4.9, 4.6, 4.4, 4.5, 4.0] }], yLabel: 'Percent', unit: '%', yMin: 3.5, yMax: 5.5, yStep: 0.5 },
    stem: 'What is the median of the eight quarterly unemployment rates shown?',
    opts: ['4.5%', '4.6%', '4.65%', '4.675%', '4.7%'],
    answer: '4.7%',
    move: 'Median: sort first; with eight values, average the 4th and 5th.',
    why: 'Sorted: 4.0, 4.4, 4.5, 4.6, 4.8, 4.9, 5.0, 5.2. The median is the mean of the 4th and 5th values: (4.6 + 4.8) / 2 = 4.7%. The mean of all eight is 37.4 / 8 = 4.675%, a different measure.',
    diag: { '4.675%': 'That is the mean. The median averages only the two middle sorted values.' },
    check: { num: 'median(val("","Q1"),val("","Q2"),val("","Q3"),val("","Q4"),val("","Q5"),val("","Q6"),val("","Q7"),val("","Q8"))' }
  },
  {
    id: 'di-044', format: 'di', topic: 'statistics', diff: 3,
    figure: { type: 'line', title: 'Daily air quality index readings', x: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'],
      series: [{ name: 'AQI', values: [42, 55, 61, 48, 70, 66, 52] }], yLabel: 'AQI' },
    stem: 'The range of the readings is what percent of the mean reading, to the nearest tenth of a percent?',
    opts: ['40.0%', '42.4%', '45.4%', '46.7%', '49.7%'],
    answer: '49.7%',
    move: 'Do the two statistics separately, then divide: range / mean.',
    why: 'Range: 70 - 42 = 28. Mean: (42 + 55 + 61 + 48 + 70 + 66 + 52) / 7 = 394 / 7, about 56.29. Range as a percent of the mean: 28 / 56.29 = 0.4975, or 49.7%. Using the median (55) instead of the mean gives 50.9%.',
    diag: {'40.0%': 'That divides by the highest reading, 70. The question asks for the mean.'},
    check: { num: '(70 - 42)/(seriessum("AQI")/7)*100', round: 1 }
  },
  {
    id: 'di-045', format: 'di', topic: 'percent', diff: 2,
    figure: { type: 'line', title: 'Plant height with and without fertilizer', x: ['0', '1', '2', '3', '4', '5'],
      series: [{ name: 'Fertilized', values: [2, 4, 7, 11, 15, 20] }, { name: 'Unfertilized', values: [2, 3, 5, 7, 9, 11] }], yLabel: 'Height (cm)', xLabel: 'Week', valueLabels: true },
    stem: 'At week 5, by what percent did the fertilized plant\'s height exceed the unfertilized plant\'s height, to the nearest tenth of a percent?',
    opts: ['45.0%', '55.0%', '81.8%', '100.0%', '181.8%'],
    answer: '81.8%',
    move: '"Exceeds by what percent" = difference / the smaller (compared) value.',
    why: 'Week 5: fertilized 20 cm, unfertilized 11 cm. Difference 9 cm. Percent above the unfertilized plant: 9 / 11 = 0.818, or 81.8%. Dividing by 20 gives 45.0%; 20 / 11 = 181.8% is the ratio, not the excess.',
    diag: { '45.0%': 'The comparison is to the unfertilized plant, so divide by 11.', '181.8%': 'Subtract 100%: 181.8% of the height means 81.8% more.' },
    check: { num: '(val("Fertilized","5")-val("Unfertilized","5"))/val("Unfertilized","5")*100', round: 1 }
  },
  {
    id: 'di-046', format: 'di', topic: 'rates', diff: 2,
    figure: { type: 'line', title: 'Website visitors per day (thousands)', x: ['Day 1', 'Day 2', 'Day 3', 'Day 4', 'Day 5', 'Day 6', 'Day 7'],
      series: [{ name: 'Visitors', values: [12, 15, 13, 18, 22, 20, 25] }], yLabel: 'Thousands' },
    stem: 'What was the average change in daily visitors per day from Day 1 to Day 7, in thousands, to the nearest hundredth?',
    opts: ['1.86', '2.17', '3.57', '13', '17.86'],
    answer: '2.17',
    move: 'Average change per step = (last - first) / number of steps, and 7 points have 6 steps.',
    why: 'From Day 1 (12 thousand) to Day 7 (25 thousand) is a change of 13 thousand over 6 day-to-day steps. 13 / 6 = 2.167, about 2.17 thousand per day. Dividing by 7 (the number of points) gives 1.86.',
    diag: { '1.86': 'Seven days have six gaps between them. Divide 13 by 6.' },
    check: { num: '(val("","Day 7") - val("","Day 1"))/6', round: 2 }
  },
  {
    id: 'di-047', format: 'di', topic: 'interest', diff: 4,
    figure: { type: 'line', title: 'Annual sales (thousands of units)', x: ['2019', '2020', '2021', '2022', '2023', '2024'],
      series: [{ name: 'Sales', values: [50, 55, 60.5, 66.55, 73.205, 80.5255] }], yLabel: 'Thousands of units' },
    stem: 'Sales grew by the same percent each year. If that continues, what will sales be in 2026, to the nearest thousand units?',
    opts: ['97', '101', '107', '112', '118'],
    answer: '97',
    move: 'Constant percent growth multiplies by the same factor every year; extend with the factor, not the last jump.',
    why: 'From 50 to 55 is 10% growth, and each later year is 1.1 times the one before. 2026 is two years after 2024: 80.53 × 1.1 × 1.1 = 97.44, about 97 thousand. Adding the last increase (about 7.3 thousand) twice gives about 95, which undercounts because the jumps keep growing.',
    diag: {'107': 'That is three years past 2024 (2027). 2026 is two years past 2024.'},
    check: { num: 'val("","2019")*(val("","2020")/val("","2019"))^7', round: 0 }
  },
  {
    id: 'di-048', format: 'di', topic: 'percent', diff: 1,
    figure: { type: 'pie', title: 'A student\'s monthly spending (dollars)', show: 'value',
      slices: [{ label: 'Rent', value: 600 }, { label: 'Food', value: 300 }, { label: 'Transport', value: 120 }, { label: 'Books', value: 80 }, { label: 'Other', value: 100 }] },
    stem: 'According to the chart, what percent of the student\'s monthly spending goes to food and transport combined?',
    opts: ['14%', '20%', '25%', '30%', '35%'],
    answer: '35%',
    move: 'Add the slices you need, then divide by the whole pie.',
    why: 'Food and transport: 300 + 120 = 420 dollars. Total: 600 + 300 + 120 + 80 + 100 = 1,200 dollars. 420 / 1,200 = 0.35, or 35%. Comparing with rent alone (420 / 600) gives 70%.',
    diag: {'25%': 'That is food alone (300 / 1,200). Add transport too.'},
    check: { num: '(slice("Food")+slice("Transport"))/pietotal()*100' }
  },
  {
    id: 'di-049', format: 'di', topic: 'percent', diff: 2,
    figure: { type: 'pie', title: 'Trail mix by weight', show: 'percent',
      slices: [{ label: 'Peanuts', value: 40 }, { label: 'Raisins', value: 25 }, { label: 'Almonds', value: 20 }, { label: 'Chocolate', value: 15 }] },
    stem: 'A 600-gram bag of this trail mix contains how many more grams of peanuts than almonds?',
    opts: ['120', '150', '180', '200', '240'],
    answer: '120',
    move: 'Percent points to grams: (difference in percent) × total.',
    why: 'Peanuts are 40% and almonds 20%, a difference of 20 percentage points. 20% of 600 grams is 120 grams. Check: peanuts 240 g, almonds 120 g, difference 120 g.',
    diag: {'240': 'That is the peanut weight alone. Subtract the 120 g of almonds.'},
    check: { num: '(slice("Peanuts")-slice("Almonds"))/pietotal()*600' }
  },
  {
    id: 'di-050', format: 'di', topic: 'percent', diff: 2,
    figure: { type: 'pie', title: 'Blood types in a sample of 250 donors', show: 'percent',
      slices: [{ label: 'O', value: 44.8 }, { label: 'A', value: 38 }, { label: 'B', value: 11.2 }, { label: 'AB', value: 6 }] },
    stem: 'How many more donors in the sample had type O blood than had type B or type AB?',
    opts: ['69', '82', '98', '112', '155'],
    answer: '69',
    move: 'Turn each percent into a count by multiplying by the sample size, then compare counts.',
    why: 'Type O: 44.8% of 250 = 112 donors. Types B and AB: 11.2% + 6% = 17.2% of 250 = 43 donors. Difference: 112 - 43 = 69. Equivalently, 27.6 percentage points of 250 is 69.',
    diag: {'112': 'That is the type O count alone. Subtract the 43 donors with B or AB.'},
    check: { num: '(slice("O") - slice("B") - slice("AB"))/pietotal()*250' }
  },
  {
    id: 'di-051', format: 'di', topic: 'percent', diff: 4,
    figure: { type: 'pie', title: 'How a city park fund is divided', show: 'percent',
      slices: [{ label: 'Maintenance', value: 45 }, { label: 'Programs', value: 25 }, { label: 'Staff', value: 20 }, { label: 'Equipment', value: 10 }] },
    stem: 'The fund totals 2.4 million dollars. Next year the total stays the same, equipment spending doubles, and the extra equipment money is taken equally from programs and staff. How much will go to programs, in thousands of dollars?',
    opts: ['360', '480', '540', '600', '720'],
    answer: '480',
    move: 'Work in dollars, move the money, then read the new slice.',
    why: 'Equipment is 10% of 2,400 thousand = 240 thousand; doubling adds 240 thousand. Half of that, 120 thousand, comes from programs. Programs start at 25% of 2,400 = 600 thousand and end at 600 - 120 = 480 thousand dollars.',
    diag: { '360': 'Only half of the extra 240 thousand comes from programs; the other half comes from staff.', '600': 'That is this year\'s amount before the shift.' },
    check: { num: 'slice("Programs")/pietotal()*2400 - slice("Equipment")/pietotal()*2400/2' }
  },
  {
    id: 'di-052', format: 'di', topic: 'ratios', diff: 3,
    figure: { type: 'pie', title: 'Market share of five carriers', show: 'percent',
      slices: [{ label: 'Apex', value: 32 }, { label: 'Beacon', value: 27 }, { label: 'Crest', value: 21 }, { label: 'Dune', value: 12 }, { label: 'Echo', value: 8 }] },
    stem: 'Next year Dune\'s share doubles, and every point Dune gains comes from Apex. What will the ratio of Apex\'s share to Dune\'s share be?',
    opts: ['2/3', '5/6', '1', '6/5', '8/3'],
    answer: '5/6',
    move: 'Shift the points first, then form the ratio from the new shares.',
    why: 'Dune goes from 12% to 24%, gaining 12 points. Apex loses those 12 points: 32% - 12% = 20%. The ratio of Apex to Dune is 20 / 24 = 5/6. Using the old shares gives 32 / 12 = 8/3.',
    diag: { '8/3': 'That uses this year\'s shares. Move the 12 points from Apex to Dune first.', '6/5': 'That is Dune to Apex. The question asks Apex to Dune.' },
    check: { num: '(slice("Apex") - slice("Dune"))/(2*slice("Dune"))' }
  },
  {
    id: 'di-053', format: 'di', topic: 'ratios', diff: 2,
    figure: { type: 'pie', title: 'Time use in a 60-minute study session', show: 'value', unit: 'min',
      slices: [{ label: 'Reading', value: 24 }, { label: 'Problems', value: 18 }, { label: 'Review', value: 12 }, { label: 'Break', value: 6 }] },
    stem: 'What fraction of the non-break time in the session was spent on problems?',
    opts: ['1/6', '1/4', '5/18', '3/10', '1/3'],
    answer: '1/3',
    move: 'Shrink the whole first when the question removes a slice: "non-break" means total minus break.',
    why: 'Non-break time: 60 - 6 = 54 minutes. Problems: 18 minutes. 18 / 54 = 1/3. Using the full hour gives 18 / 60 = 3/10.',
    diag: {'3/10': 'That divides by all 60 minutes. Remove the 6-minute break first.'},
    check: { num: 'slice("Problems")/(pietotal() - slice("Break"))' }
  },
  {
    id: 'di-054', format: 'di', topic: 'percent', diff: 3,
    figure: { type: 'pie', title: 'Sources of a school\'s electricity', show: 'percent',
      slices: [{ label: 'Grid', value: 55 }, { label: 'Solar', value: 25 }, { label: 'Wind', value: 15 }, { label: 'Generator', value: 5 }] },
    stem: 'The school used 80,000 kWh in total. Next year total use stays the same, and solar output rises by 4,000 kWh, replacing grid power. What percent of the total will solar supply?',
    opts: ['30%', '31.6%', '35%', '45%', '55%'],
    answer: '30%',
    move: 'Percent to amount, adjust the amount, then back to percent of the (unchanged) total.',
    why: 'Solar now: 25% of 80,000 = 20,000 kWh. Next year: 20,000 + 4,000 = 24,000 kWh. The total stays 80,000, so solar supplies 24,000 / 80,000 = 30%. Dividing by 76,000 (as if the total shrank) gives 31.6%.',
    diag: {'31.6%': 'The total stays at 80,000 because solar replaces grid power one for one.'},
    check: { num: '(slice("Solar")/pietotal()*80000 + 4000)/80000*100' }
  },
  {
    id: 'di-055', format: 'di', topic: 'ratios', diff: 2,
    figure: { type: 'pie', title: 'Pets in 160 surveyed households', show: 'value',
      slices: [{ label: 'Dog', value: 64 }, { label: 'Cat', value: 48 }, { label: 'Fish', value: 24 }, { label: 'Bird', value: 16 }, { label: 'Other', value: 8 }] },
    stem: 'What is the ratio of cat households to fish and bird households combined?',
    opts: ['3/5', '2/3', '5/6', '1', '6/5'],
    answer: '6/5',
    move: 'Combine the second group before forming the ratio.',
    why: 'Fish and bird together: 24 + 16 = 40. Cat: 48. Ratio 48 / 40 = 6/5. Flipping it gives 5/6, and comparing cat with fish alone gives 2.',
    diag: {'5/6': 'That is fish and bird to cat, the reverse order.'},
    check: { num: 'slice("Cat")/(slice("Fish")+slice("Bird"))' }
  },
  {
    id: 'di-056', format: 'di', topic: 'percent', diff: 1,
    figure: { type: 'pie', title: 'Final grades in a class of 40 students', show: 'percent',
      slices: [{ label: 'A', value: 15 }, { label: 'B', value: 35 }, { label: 'C', value: 30 }, { label: 'D', value: 15 }, { label: 'F', value: 5 }] },
    stem: 'How many students in the class earned a grade of C or better?',
    opts: ['12', '20', '26', '32', '34'],
    answer: '32',
    move: '"C or better" means C, B, and A together.',
    why: 'A + B + C = 15% + 35% + 30% = 80%. 80% of 40 students is 32. Leaving out C gives 50%, or 20 students.',
    diag: { '20': 'Include the C grades: "or better" keeps C itself.' },
    check: { num: '(slice("A")+slice("B")+slice("C"))/pietotal()*40' }
  },
  {
    id: 'di-057', format: 'di', topic: 'ratios', diff: 2,
    figure: { type: 'pie', title: 'A nonprofit\'s yearly spending', show: 'percent',
      slices: [{ label: 'Programs', value: 72 }, { label: 'Fundraising', value: 18 }, { label: 'Admin', value: 10 }] },
    stem: 'If the nonprofit spent 45,000 dollars on admin, how much did it spend on programs?',
    opts: ['81,000 dollars', '108,000 dollars', '162,000 dollars', '250,000 dollars', '324,000 dollars'],
    answer: '324,000 dollars',
    move: 'Use the known slice to find the whole, or scale directly by the ratio of percents.',
    why: 'Admin is 10%, so the total is 45,000 / 0.10 = 450,000 dollars. Programs are 72% of that: 0.72 × 450,000 = 324,000 dollars. Shortcut: programs / admin = 72 / 10 = 7.2, and 7.2 × 45,000 = 324,000.',
    diag: {'81,000 dollars': 'That is fundraising, 18% of the 450,000 dollar total.'},
    check: { num: '45000/slice("Admin")*slice("Programs")' }
  },
  {
    id: 'di-058', format: 'di', topic: 'percent', diff: 4,
    figure: { type: 'pie', title: 'Recycled material by weight', show: 'value', unit: 'tons',
      slices: [{ label: 'Paper', value: 18 }, { label: 'Plastic', value: 9 }, { label: 'Glass', value: 6 }, { label: 'Metal', value: 3 }] },
    stem: 'Next month paper drops by one third and metal doubles, while plastic and glass stay the same. What percent of the new total will be metal, to the nearest tenth of a percent?',
    opts: ['8.3%', '12.5%', '15.4%', '16.7%', '18.2%'],
    answer: '18.2%',
    move: 'Rebuild the whole after a change; the old total is no longer the base.',
    why: 'New amounts: paper 18 - 6 = 12, plastic 9, glass 6, metal 3 × 2 = 6. New total: 12 + 9 + 6 + 6 = 33 tons. Metal: 6 / 33 = 0.1818, or 18.2%. Dividing by the old total, 36, gives 16.7%.',
    diag: {'16.7%': 'The total changed to 33 tons. Divide by the new total.'},
    check: { num: '2*slice("Metal")/(slice("Paper")*2/3 + slice("Plastic") + slice("Glass") + 2*slice("Metal"))*100', round: 1 }
  },
  {
    id: 'di-059', format: 'di', topic: 'percent', diff: 2,
    figure: { type: 'pie', title: 'How 600 students get to campus', show: 'percent',
      slices: [{ label: 'Walk', value: 30 }, { label: 'Bus', value: 25 }, { label: 'Car', value: 20 }, { label: 'Bike', value: 15 }, { label: 'Train', value: 10 }] },
    stem: 'How many more students walk to campus than bike or take the train?',
    opts: ['10', '30', '60', '90', '150'],
    answer: '30',
    move: 'Subtract percentages first, then convert once: (30% - 25%) of 600.',
    why: 'Walk: 30%. Bike or train: 15% + 10% = 25%. Difference: 5 percentage points. 5% of 600 = 30 students.',
    diag: { '90': 'That compares walking with biking only (15 points). Train riders count too.' },
    check: { num: '(slice("Walk") - slice("Bike") - slice("Train"))/pietotal()*600' }
  },
  {
    id: 'di-060', format: 'di', topic: 'percent', diff: 2,
    figure: { type: 'pie', title: 'Sections of a 120-minute practice exam', show: 'value', unit: 'min',
      slices: [{ label: 'Section 1', value: 45 }, { label: 'Section 2', value: 30 }, { label: 'Section 3', value: 25 }, { label: 'Section 4', value: 20 }] },
    stem: 'A student finishes every section in 80% of its allotted time. In total, how many minutes of the exam go unused?',
    opts: ['24', '30', '36', '48', '96'],
    answer: '24',
    move: 'If every part shrinks by the same percent, apply it to the whole at once.',
    why: 'Each section uses 80% of its time, so 20% of every section goes unused. Since that is the same for all sections, 20% of the whole 120 minutes is unused: 24 minutes. 96 is the time used, not the time left over.',
    diag: {'96': 'That is the time the student used. The question asks for the unused time.'},
    check: { num: 'pietotal()*(1 - 0.8)' }
  }
];
